// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "XCSDHomework.pb.h"
// @@protoc_insertion_point(imports)

@class ObjectiveCFileOptions;
@class ObjectiveCFileOptionsBuilder;
@class PBDescriptorProto;
@class PBDescriptorProtoBuilder;
@class PBDescriptorProtoExtensionRange;
@class PBDescriptorProtoExtensionRangeBuilder;
@class PBEnumDescriptorProto;
@class PBEnumDescriptorProtoBuilder;
@class PBEnumOptions;
@class PBEnumOptionsBuilder;
@class PBEnumValueDescriptorProto;
@class PBEnumValueDescriptorProtoBuilder;
@class PBEnumValueOptions;
@class PBEnumValueOptionsBuilder;
@class PBFieldDescriptorProto;
@class PBFieldDescriptorProtoBuilder;
@class PBFieldOptions;
@class PBFieldOptionsBuilder;
@class PBFileDescriptorProto;
@class PBFileDescriptorProtoBuilder;
@class PBFileDescriptorSet;
@class PBFileDescriptorSetBuilder;
@class PBFileOptions;
@class PBFileOptionsBuilder;
@class PBMessageOptions;
@class PBMessageOptionsBuilder;
@class PBMethodDescriptorProto;
@class PBMethodDescriptorProtoBuilder;
@class PBMethodOptions;
@class PBMethodOptionsBuilder;
@class PBServiceDescriptorProto;
@class PBServiceDescriptorProtoBuilder;
@class PBServiceOptions;
@class PBServiceOptionsBuilder;
@class PBSourceCodeInfo;
@class PBSourceCodeInfoBuilder;
@class PBSourceCodeInfoLocation;
@class PBSourceCodeInfoLocationBuilder;
@class PBUninterpretedOption;
@class PBUninterpretedOptionBuilder;
@class PBUninterpretedOptionNamePart;
@class PBUninterpretedOptionNamePartBuilder;
@class XCSDPBAbilityDetail;
@class XCSDPBAbilityDetailBuilder;
@class XCSDPBAbilityScoreRequest;
@class XCSDPBAbilityScoreRequestBuilder;
@class XCSDPBAbilityScoreResponse;
@class XCSDPBAbilityScoreResponseBuilder;
@class XCSDPBAbilityScoreResponseGameScore;
@class XCSDPBAbilityScoreResponseGameScoreBuilder;
@class XCSDPBAbilityStatRequest;
@class XCSDPBAbilityStatRequestBuilder;
@class XCSDPBAbilityStatResponse;
@class XCSDPBAbilityStatResponseBuilder;
@class XCSDPBAbilityStatResponsePoint;
@class XCSDPBAbilityStatResponsePointBuilder;
@class XCSDPBAbilityValue;
@class XCSDPBAbilityValueBuilder;
@class XCSDPBClassAbilityRankingRequest;
@class XCSDPBClassAbilityRankingRequestBuilder;
@class XCSDPBClassAbilityRankingResponse;
@class XCSDPBClassAbilityRankingResponseBuilder;
@class XCSDPBClassHomework;
@class XCSDPBClassHomeworkBuilder;
@class XCSDPBDeleteHomeworkNoticeRequest;
@class XCSDPBDeleteHomeworkNoticeRequestBuilder;
@class XCSDPBDeleteHomeworkNoticeResponse;
@class XCSDPBDeleteHomeworkNoticeResponseBuilder;
@class XCSDPBGenerateHomeworkRequest;
@class XCSDPBGenerateHomeworkRequestBuilder;
@class XCSDPBGenerateHomeworkResponse;
@class XCSDPBGenerateHomeworkResponseBuilder;
@class XCSDPBGenerateHomeworkResponseUserHomework;
@class XCSDPBGenerateHomeworkResponseUserHomeworkBuilder;
@class XCSDPBHomework;
@class XCSDPBHomeworkBuilder;
@class XCSDPBHomeworkCalendarRequest;
@class XCSDPBHomeworkCalendarRequestBuilder;
@class XCSDPBHomeworkCalendarResponse;
@class XCSDPBHomeworkCalendarResponseBuilder;
@class XCSDPBHomeworkListRequest;
@class XCSDPBHomeworkListRequestBuilder;
@class XCSDPBHomeworkListResponse;
@class XCSDPBHomeworkListResponseBuilder;
@class XCSDPBHomeworkMember;
@class XCSDPBHomeworkMemberBuilder;
@class XCSDPBHomeworkMemberListRequest;
@class XCSDPBHomeworkMemberListRequestBuilder;
@class XCSDPBHomeworkMemberListResponse;
@class XCSDPBHomeworkMemberListResponseBuilder;
@class XCSDPBHomeworkRankingRequest;
@class XCSDPBHomeworkRankingRequestBuilder;
@class XCSDPBHomeworkRankingResponse;
@class XCSDPBHomeworkRankingResponseBuilder;
@class XCSDPBHomeworkRemainingCountRequest;
@class XCSDPBHomeworkRemainingCountRequestBuilder;
@class XCSDPBHomeworkRemainingCountResponse;
@class XCSDPBHomeworkRemainingCountResponseBuilder;
@class XCSDPBHomeworkSentListRequest;
@class XCSDPBHomeworkSentListRequestBuilder;
@class XCSDPBHomeworkSentListResponse;
@class XCSDPBHomeworkSentListResponseBuilder;
@class XCSDPBReadHomeworkNoticeRequest;
@class XCSDPBReadHomeworkNoticeRequestBuilder;
@class XCSDPBReadHomeworkNoticeResponse;
@class XCSDPBReadHomeworkNoticeResponseBuilder;
@class XCSDPBSendHomeworkRequest;
@class XCSDPBSendHomeworkRequestBuilder;
@class XCSDPBSendHomeworkResponse;
@class XCSDPBSendHomeworkResponseBuilder;
@class XCSDPBUserRank;
@class XCSDPBUserRankBuilder;


typedef NS_ENUM(SInt32, XCSDPBAbility) {
  XCSDPBAbilityAttention = 1,
  XCSDPBAbilityMemory = 2,
  XCSDPBAbilityReaction = 3,
  XCSDPBAbilityReasoning = 4,
  XCSDPBAbilitySpatialThinking = 5,
};

BOOL XCSDPBAbilityIsValidValue(XCSDPBAbility value);
NSString *NSStringFromXCSDPBAbility(XCSDPBAbility value);


@interface XCSDPBXcsdlearningAbilityRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define AbilityValue_ability @"ability"
#define AbilityValue_value @"value"
@interface XCSDPBAbilityValue : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasValue_:1;
  BOOL hasAbility_:1;
  SInt32 value;
  XCSDPBAbility ability;
}
- (BOOL) hasAbility;
- (BOOL) hasValue;
@property (readonly) XCSDPBAbility ability;
@property (readonly) SInt32 value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBAbilityValueBuilder*) builder;
+ (XCSDPBAbilityValueBuilder*) builder;
+ (XCSDPBAbilityValueBuilder*) builderWithPrototype:(XCSDPBAbilityValue*) prototype;
- (XCSDPBAbilityValueBuilder*) toBuilder;

+ (XCSDPBAbilityValue*) parseFromData:(NSData*) data;
+ (XCSDPBAbilityValue*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityValue*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBAbilityValue*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityValue*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBAbilityValue*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBAbilityValueBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBAbilityValue* resultAbilityValue;
}

- (XCSDPBAbilityValue*) defaultInstance;

- (XCSDPBAbilityValueBuilder*) clear;
- (XCSDPBAbilityValueBuilder*) clone;

- (XCSDPBAbilityValue*) build;
- (XCSDPBAbilityValue*) buildPartial;

- (XCSDPBAbilityValueBuilder*) mergeFrom:(XCSDPBAbilityValue*) other;
- (XCSDPBAbilityValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBAbilityValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAbility;
- (XCSDPBAbility) ability;
- (XCSDPBAbilityValueBuilder*) setAbility:(XCSDPBAbility) value;
- (XCSDPBAbilityValueBuilder*) clearAbility;

- (BOOL) hasValue;
- (SInt32) value;
- (XCSDPBAbilityValueBuilder*) setValue:(SInt32) value;
- (XCSDPBAbilityValueBuilder*) clearValue;
@end

#define ClassAbilityRankingRequest_classId @"classId"
@interface XCSDPBClassAbilityRankingRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasClassId_:1;
  SInt64 classId;
}
- (BOOL) hasClassId;
@property (readonly) SInt64 classId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBClassAbilityRankingRequestBuilder*) builder;
+ (XCSDPBClassAbilityRankingRequestBuilder*) builder;
+ (XCSDPBClassAbilityRankingRequestBuilder*) builderWithPrototype:(XCSDPBClassAbilityRankingRequest*) prototype;
- (XCSDPBClassAbilityRankingRequestBuilder*) toBuilder;

+ (XCSDPBClassAbilityRankingRequest*) parseFromData:(NSData*) data;
+ (XCSDPBClassAbilityRankingRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBClassAbilityRankingRequest*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBClassAbilityRankingRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBClassAbilityRankingRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBClassAbilityRankingRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBClassAbilityRankingRequestBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBClassAbilityRankingRequest* resultClassAbilityRankingRequest;
}

- (XCSDPBClassAbilityRankingRequest*) defaultInstance;

- (XCSDPBClassAbilityRankingRequestBuilder*) clear;
- (XCSDPBClassAbilityRankingRequestBuilder*) clone;

- (XCSDPBClassAbilityRankingRequest*) build;
- (XCSDPBClassAbilityRankingRequest*) buildPartial;

- (XCSDPBClassAbilityRankingRequestBuilder*) mergeFrom:(XCSDPBClassAbilityRankingRequest*) other;
- (XCSDPBClassAbilityRankingRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBClassAbilityRankingRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasClassId;
- (SInt64) classId;
- (XCSDPBClassAbilityRankingRequestBuilder*) setClassId:(SInt64) value;
- (XCSDPBClassAbilityRankingRequestBuilder*) clearClassId;
@end

#define ClassAbilityRankingResponse_rankList @"rankList"
@interface XCSDPBClassAbilityRankingResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * rankListArray;
}
@property (readonly, strong) NSArray * rankList;
- (XCSDPBUserRank*)rankListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBClassAbilityRankingResponseBuilder*) builder;
+ (XCSDPBClassAbilityRankingResponseBuilder*) builder;
+ (XCSDPBClassAbilityRankingResponseBuilder*) builderWithPrototype:(XCSDPBClassAbilityRankingResponse*) prototype;
- (XCSDPBClassAbilityRankingResponseBuilder*) toBuilder;

+ (XCSDPBClassAbilityRankingResponse*) parseFromData:(NSData*) data;
+ (XCSDPBClassAbilityRankingResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBClassAbilityRankingResponse*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBClassAbilityRankingResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBClassAbilityRankingResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBClassAbilityRankingResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBClassAbilityRankingResponseBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBClassAbilityRankingResponse* resultClassAbilityRankingResponse;
}

- (XCSDPBClassAbilityRankingResponse*) defaultInstance;

- (XCSDPBClassAbilityRankingResponseBuilder*) clear;
- (XCSDPBClassAbilityRankingResponseBuilder*) clone;

- (XCSDPBClassAbilityRankingResponse*) build;
- (XCSDPBClassAbilityRankingResponse*) buildPartial;

- (XCSDPBClassAbilityRankingResponseBuilder*) mergeFrom:(XCSDPBClassAbilityRankingResponse*) other;
- (XCSDPBClassAbilityRankingResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBClassAbilityRankingResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)rankList;
- (XCSDPBUserRank*)rankListAtIndex:(NSUInteger)index;
- (XCSDPBClassAbilityRankingResponseBuilder *)addRankList:(XCSDPBUserRank*)value;
- (XCSDPBClassAbilityRankingResponseBuilder *)setRankListArray:(NSArray *)array;
- (XCSDPBClassAbilityRankingResponseBuilder *)clearRankList;
@end

#define AbilityStatRequest_childUserId @"childUserId"
@interface XCSDPBAbilityStatRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChildUserId_:1;
  SInt64 childUserId;
}
- (BOOL) hasChildUserId;
@property (readonly) SInt64 childUserId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBAbilityStatRequestBuilder*) builder;
+ (XCSDPBAbilityStatRequestBuilder*) builder;
+ (XCSDPBAbilityStatRequestBuilder*) builderWithPrototype:(XCSDPBAbilityStatRequest*) prototype;
- (XCSDPBAbilityStatRequestBuilder*) toBuilder;

+ (XCSDPBAbilityStatRequest*) parseFromData:(NSData*) data;
+ (XCSDPBAbilityStatRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityStatRequest*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBAbilityStatRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityStatRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBAbilityStatRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBAbilityStatRequestBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBAbilityStatRequest* resultAbilityStatRequest;
}

- (XCSDPBAbilityStatRequest*) defaultInstance;

- (XCSDPBAbilityStatRequestBuilder*) clear;
- (XCSDPBAbilityStatRequestBuilder*) clone;

- (XCSDPBAbilityStatRequest*) build;
- (XCSDPBAbilityStatRequest*) buildPartial;

- (XCSDPBAbilityStatRequestBuilder*) mergeFrom:(XCSDPBAbilityStatRequest*) other;
- (XCSDPBAbilityStatRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBAbilityStatRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChildUserId;
- (SInt64) childUserId;
- (XCSDPBAbilityStatRequestBuilder*) setChildUserId:(SInt64) value;
- (XCSDPBAbilityStatRequestBuilder*) clearChildUserId;
@end

#define AbilityDetail_ability @"ability"
#define AbilityDetail_level @"level"
#define AbilityDetail_avgLevel @"avgLevel"
#define AbilityDetail_percentage @"percentage"
#define AbilityDetail_score @"score"
#define AbilityDetail_maxScore @"maxScore"
#define AbilityDetail_gradeAvgLevel @"gradeAvgLevel"
@interface XCSDPBAbilityDetail : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPercentage_:1;
  BOOL hasLevel_:1;
  BOOL hasAvgLevel_:1;
  BOOL hasScore_:1;
  BOOL hasMaxScore_:1;
  BOOL hasAbility_:1;
  Float64 percentage;
  SInt32 level;
  SInt32 avgLevel;
  SInt32 score;
  SInt32 maxScore;
  XCSDPBAbility ability;
  PBAppendableArray * gradeAvgLevelArray;
}
- (BOOL) hasAbility;
- (BOOL) hasLevel;
- (BOOL) hasAvgLevel;
- (BOOL) hasPercentage;
- (BOOL) hasScore;
- (BOOL) hasMaxScore;
@property (readonly) XCSDPBAbility ability;
@property (readonly) SInt32 level;
@property (readonly) SInt32 avgLevel;
@property (readonly) Float64 percentage;
@property (readonly) SInt32 score;
@property (readonly) SInt32 maxScore;
@property (readonly, strong) PBArray * gradeAvgLevel;
- (SInt32)gradeAvgLevelAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBAbilityDetailBuilder*) builder;
+ (XCSDPBAbilityDetailBuilder*) builder;
+ (XCSDPBAbilityDetailBuilder*) builderWithPrototype:(XCSDPBAbilityDetail*) prototype;
- (XCSDPBAbilityDetailBuilder*) toBuilder;

+ (XCSDPBAbilityDetail*) parseFromData:(NSData*) data;
+ (XCSDPBAbilityDetail*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityDetail*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBAbilityDetail*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityDetail*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBAbilityDetail*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBAbilityDetailBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBAbilityDetail* resultAbilityDetail;
}

- (XCSDPBAbilityDetail*) defaultInstance;

- (XCSDPBAbilityDetailBuilder*) clear;
- (XCSDPBAbilityDetailBuilder*) clone;

- (XCSDPBAbilityDetail*) build;
- (XCSDPBAbilityDetail*) buildPartial;

- (XCSDPBAbilityDetailBuilder*) mergeFrom:(XCSDPBAbilityDetail*) other;
- (XCSDPBAbilityDetailBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBAbilityDetailBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAbility;
- (XCSDPBAbility) ability;
- (XCSDPBAbilityDetailBuilder*) setAbility:(XCSDPBAbility) value;
- (XCSDPBAbilityDetailBuilder*) clearAbility;

- (BOOL) hasLevel;
- (SInt32) level;
- (XCSDPBAbilityDetailBuilder*) setLevel:(SInt32) value;
- (XCSDPBAbilityDetailBuilder*) clearLevel;

- (BOOL) hasAvgLevel;
- (SInt32) avgLevel;
- (XCSDPBAbilityDetailBuilder*) setAvgLevel:(SInt32) value;
- (XCSDPBAbilityDetailBuilder*) clearAvgLevel;

- (BOOL) hasPercentage;
- (Float64) percentage;
- (XCSDPBAbilityDetailBuilder*) setPercentage:(Float64) value;
- (XCSDPBAbilityDetailBuilder*) clearPercentage;

- (BOOL) hasScore;
- (SInt32) score;
- (XCSDPBAbilityDetailBuilder*) setScore:(SInt32) value;
- (XCSDPBAbilityDetailBuilder*) clearScore;

- (BOOL) hasMaxScore;
- (SInt32) maxScore;
- (XCSDPBAbilityDetailBuilder*) setMaxScore:(SInt32) value;
- (XCSDPBAbilityDetailBuilder*) clearMaxScore;

- (PBAppendableArray *)gradeAvgLevel;
- (SInt32)gradeAvgLevelAtIndex:(NSUInteger)index;
- (XCSDPBAbilityDetailBuilder *)addGradeAvgLevel:(SInt32)value;
- (XCSDPBAbilityDetailBuilder *)setGradeAvgLevelArray:(NSArray *)array;
- (XCSDPBAbilityDetailBuilder *)setGradeAvgLevelValues:(const SInt32 *)values count:(NSUInteger)count;
- (XCSDPBAbilityDetailBuilder *)clearGradeAvgLevel;
@end

#define AbilityStatResponse_details @"details"
#define AbilityStatResponse_totalAbilityLevel @"totalAbilityLevel"
#define AbilityStatResponse_totalAbilityPercentage @"totalAbilityPercentage"
#define AbilityStatResponse_abilityQuotient @"abilityQuotient"
#define AbilityStatResponse_maxAbilityQuotient @"maxAbilityQuotient"
#define AbilityStatResponse_abilityChart @"abilityChart"
@interface XCSDPBAbilityStatResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTotalAbilityPercentage_:1;
  BOOL hasTotalAbilityLevel_:1;
  BOOL hasAbilityQuotient_:1;
  BOOL hasMaxAbilityQuotient_:1;
  Float64 totalAbilityPercentage;
  SInt32 totalAbilityLevel;
  SInt32 abilityQuotient;
  SInt32 maxAbilityQuotient;
  NSMutableArray * detailsArray;
  NSMutableArray * abilityChartArray;
}
- (BOOL) hasTotalAbilityLevel;
- (BOOL) hasTotalAbilityPercentage;
- (BOOL) hasAbilityQuotient;
- (BOOL) hasMaxAbilityQuotient;
@property (readonly, strong) NSArray * details;
@property (readonly) SInt32 totalAbilityLevel;
@property (readonly) Float64 totalAbilityPercentage;
@property (readonly) SInt32 abilityQuotient;
@property (readonly) SInt32 maxAbilityQuotient;
@property (readonly, strong) NSArray * abilityChart;
- (XCSDPBAbilityDetail*)detailsAtIndex:(NSUInteger)index;
- (XCSDPBAbilityStatResponsePoint*)abilityChartAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBAbilityStatResponseBuilder*) builder;
+ (XCSDPBAbilityStatResponseBuilder*) builder;
+ (XCSDPBAbilityStatResponseBuilder*) builderWithPrototype:(XCSDPBAbilityStatResponse*) prototype;
- (XCSDPBAbilityStatResponseBuilder*) toBuilder;

+ (XCSDPBAbilityStatResponse*) parseFromData:(NSData*) data;
+ (XCSDPBAbilityStatResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityStatResponse*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBAbilityStatResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityStatResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBAbilityStatResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define Point_number @"number"
#define Point_score @"score"
@interface XCSDPBAbilityStatResponsePoint : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasNumber_:1;
  BOOL hasScore_:1;
  SInt32 number;
  SInt32 score;
}
- (BOOL) hasNumber;
- (BOOL) hasScore;
@property (readonly) SInt32 number;
@property (readonly) SInt32 score;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBAbilityStatResponsePointBuilder*) builder;
+ (XCSDPBAbilityStatResponsePointBuilder*) builder;
+ (XCSDPBAbilityStatResponsePointBuilder*) builderWithPrototype:(XCSDPBAbilityStatResponsePoint*) prototype;
- (XCSDPBAbilityStatResponsePointBuilder*) toBuilder;

+ (XCSDPBAbilityStatResponsePoint*) parseFromData:(NSData*) data;
+ (XCSDPBAbilityStatResponsePoint*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityStatResponsePoint*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBAbilityStatResponsePoint*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityStatResponsePoint*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBAbilityStatResponsePoint*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBAbilityStatResponsePointBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBAbilityStatResponsePoint* resultPoint;
}

- (XCSDPBAbilityStatResponsePoint*) defaultInstance;

- (XCSDPBAbilityStatResponsePointBuilder*) clear;
- (XCSDPBAbilityStatResponsePointBuilder*) clone;

- (XCSDPBAbilityStatResponsePoint*) build;
- (XCSDPBAbilityStatResponsePoint*) buildPartial;

- (XCSDPBAbilityStatResponsePointBuilder*) mergeFrom:(XCSDPBAbilityStatResponsePoint*) other;
- (XCSDPBAbilityStatResponsePointBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBAbilityStatResponsePointBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNumber;
- (SInt32) number;
- (XCSDPBAbilityStatResponsePointBuilder*) setNumber:(SInt32) value;
- (XCSDPBAbilityStatResponsePointBuilder*) clearNumber;

- (BOOL) hasScore;
- (SInt32) score;
- (XCSDPBAbilityStatResponsePointBuilder*) setScore:(SInt32) value;
- (XCSDPBAbilityStatResponsePointBuilder*) clearScore;
@end

@interface XCSDPBAbilityStatResponseBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBAbilityStatResponse* resultAbilityStatResponse;
}

- (XCSDPBAbilityStatResponse*) defaultInstance;

- (XCSDPBAbilityStatResponseBuilder*) clear;
- (XCSDPBAbilityStatResponseBuilder*) clone;

- (XCSDPBAbilityStatResponse*) build;
- (XCSDPBAbilityStatResponse*) buildPartial;

- (XCSDPBAbilityStatResponseBuilder*) mergeFrom:(XCSDPBAbilityStatResponse*) other;
- (XCSDPBAbilityStatResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBAbilityStatResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)details;
- (XCSDPBAbilityDetail*)detailsAtIndex:(NSUInteger)index;
- (XCSDPBAbilityStatResponseBuilder *)addDetails:(XCSDPBAbilityDetail*)value;
- (XCSDPBAbilityStatResponseBuilder *)setDetailsArray:(NSArray *)array;
- (XCSDPBAbilityStatResponseBuilder *)clearDetails;

- (BOOL) hasTotalAbilityLevel;
- (SInt32) totalAbilityLevel;
- (XCSDPBAbilityStatResponseBuilder*) setTotalAbilityLevel:(SInt32) value;
- (XCSDPBAbilityStatResponseBuilder*) clearTotalAbilityLevel;

- (BOOL) hasTotalAbilityPercentage;
- (Float64) totalAbilityPercentage;
- (XCSDPBAbilityStatResponseBuilder*) setTotalAbilityPercentage:(Float64) value;
- (XCSDPBAbilityStatResponseBuilder*) clearTotalAbilityPercentage;

- (BOOL) hasAbilityQuotient;
- (SInt32) abilityQuotient;
- (XCSDPBAbilityStatResponseBuilder*) setAbilityQuotient:(SInt32) value;
- (XCSDPBAbilityStatResponseBuilder*) clearAbilityQuotient;

- (BOOL) hasMaxAbilityQuotient;
- (SInt32) maxAbilityQuotient;
- (XCSDPBAbilityStatResponseBuilder*) setMaxAbilityQuotient:(SInt32) value;
- (XCSDPBAbilityStatResponseBuilder*) clearMaxAbilityQuotient;

- (NSMutableArray *)abilityChart;
- (XCSDPBAbilityStatResponsePoint*)abilityChartAtIndex:(NSUInteger)index;
- (XCSDPBAbilityStatResponseBuilder *)addAbilityChart:(XCSDPBAbilityStatResponsePoint*)value;
- (XCSDPBAbilityStatResponseBuilder *)setAbilityChartArray:(NSArray *)array;
- (XCSDPBAbilityStatResponseBuilder *)clearAbilityChart;
@end

#define AbilityScoreRequest_userId @"userId"
#define AbilityScoreRequest_ability @"ability"
@interface XCSDPBAbilityScoreRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasAbility_:1;
  SInt64 userId;
  XCSDPBAbility ability;
}
- (BOOL) hasUserId;
- (BOOL) hasAbility;
@property (readonly) SInt64 userId;
@property (readonly) XCSDPBAbility ability;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBAbilityScoreRequestBuilder*) builder;
+ (XCSDPBAbilityScoreRequestBuilder*) builder;
+ (XCSDPBAbilityScoreRequestBuilder*) builderWithPrototype:(XCSDPBAbilityScoreRequest*) prototype;
- (XCSDPBAbilityScoreRequestBuilder*) toBuilder;

+ (XCSDPBAbilityScoreRequest*) parseFromData:(NSData*) data;
+ (XCSDPBAbilityScoreRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityScoreRequest*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBAbilityScoreRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityScoreRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBAbilityScoreRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBAbilityScoreRequestBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBAbilityScoreRequest* resultAbilityScoreRequest;
}

- (XCSDPBAbilityScoreRequest*) defaultInstance;

- (XCSDPBAbilityScoreRequestBuilder*) clear;
- (XCSDPBAbilityScoreRequestBuilder*) clone;

- (XCSDPBAbilityScoreRequest*) build;
- (XCSDPBAbilityScoreRequest*) buildPartial;

- (XCSDPBAbilityScoreRequestBuilder*) mergeFrom:(XCSDPBAbilityScoreRequest*) other;
- (XCSDPBAbilityScoreRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBAbilityScoreRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (SInt64) userId;
- (XCSDPBAbilityScoreRequestBuilder*) setUserId:(SInt64) value;
- (XCSDPBAbilityScoreRequestBuilder*) clearUserId;

- (BOOL) hasAbility;
- (XCSDPBAbility) ability;
- (XCSDPBAbilityScoreRequestBuilder*) setAbility:(XCSDPBAbility) value;
- (XCSDPBAbilityScoreRequestBuilder*) clearAbility;
@end

#define AbilityScoreResponse_totalScore @"totalScore"
#define AbilityScoreResponse_gameList @"gameList"
@interface XCSDPBAbilityScoreResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTotalScore_:1;
  SInt32 totalScore;
  NSMutableArray * gameListArray;
}
- (BOOL) hasTotalScore;
@property (readonly) SInt32 totalScore;
@property (readonly, strong) NSArray * gameList;
- (XCSDPBAbilityScoreResponseGameScore*)gameListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBAbilityScoreResponseBuilder*) builder;
+ (XCSDPBAbilityScoreResponseBuilder*) builder;
+ (XCSDPBAbilityScoreResponseBuilder*) builderWithPrototype:(XCSDPBAbilityScoreResponse*) prototype;
- (XCSDPBAbilityScoreResponseBuilder*) toBuilder;

+ (XCSDPBAbilityScoreResponse*) parseFromData:(NSData*) data;
+ (XCSDPBAbilityScoreResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityScoreResponse*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBAbilityScoreResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityScoreResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBAbilityScoreResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define GameScore_gameId @"gameId"
#define GameScore_gameName @"gameName"
#define GameScore_score @"score"
#define GameScore_bestLevel @"bestLevel"
#define GameScore_percentage @"percentage"
#define GameScore_color @"color"
#define GameScore_classRank @"classRank"
@interface XCSDPBAbilityScoreResponseGameScore : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPercentage_:1;
  BOOL hasGameId_:1;
  BOOL hasScore_:1;
  BOOL hasBestLevel_:1;
  BOOL hasClassRank_:1;
  BOOL hasGameName_:1;
  BOOL hasColor_:1;
  Float64 percentage;
  SInt32 gameId;
  SInt32 score;
  SInt32 bestLevel;
  SInt32 classRank;
  NSString* gameName;
  NSString* color;
}
- (BOOL) hasGameId;
- (BOOL) hasGameName;
- (BOOL) hasScore;
- (BOOL) hasBestLevel;
- (BOOL) hasPercentage;
- (BOOL) hasColor;
- (BOOL) hasClassRank;
@property (readonly) SInt32 gameId;
@property (readonly, strong) NSString* gameName;
@property (readonly) SInt32 score;
@property (readonly) SInt32 bestLevel;
@property (readonly) Float64 percentage;
@property (readonly, strong) NSString* color;
@property (readonly) SInt32 classRank;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) builder;
+ (XCSDPBAbilityScoreResponseGameScoreBuilder*) builder;
+ (XCSDPBAbilityScoreResponseGameScoreBuilder*) builderWithPrototype:(XCSDPBAbilityScoreResponseGameScore*) prototype;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) toBuilder;

+ (XCSDPBAbilityScoreResponseGameScore*) parseFromData:(NSData*) data;
+ (XCSDPBAbilityScoreResponseGameScore*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityScoreResponseGameScore*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBAbilityScoreResponseGameScore*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityScoreResponseGameScore*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBAbilityScoreResponseGameScore*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBAbilityScoreResponseGameScoreBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBAbilityScoreResponseGameScore* resultGameScore;
}

- (XCSDPBAbilityScoreResponseGameScore*) defaultInstance;

- (XCSDPBAbilityScoreResponseGameScoreBuilder*) clear;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) clone;

- (XCSDPBAbilityScoreResponseGameScore*) build;
- (XCSDPBAbilityScoreResponseGameScore*) buildPartial;

- (XCSDPBAbilityScoreResponseGameScoreBuilder*) mergeFrom:(XCSDPBAbilityScoreResponseGameScore*) other;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGameId;
- (SInt32) gameId;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) setGameId:(SInt32) value;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) clearGameId;

- (BOOL) hasGameName;
- (NSString*) gameName;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) setGameName:(NSString*) value;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) clearGameName;

- (BOOL) hasScore;
- (SInt32) score;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) setScore:(SInt32) value;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) clearScore;

- (BOOL) hasBestLevel;
- (SInt32) bestLevel;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) setBestLevel:(SInt32) value;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) clearBestLevel;

- (BOOL) hasPercentage;
- (Float64) percentage;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) setPercentage:(Float64) value;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) clearPercentage;

- (BOOL) hasColor;
- (NSString*) color;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) setColor:(NSString*) value;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) clearColor;

- (BOOL) hasClassRank;
- (SInt32) classRank;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) setClassRank:(SInt32) value;
- (XCSDPBAbilityScoreResponseGameScoreBuilder*) clearClassRank;
@end

@interface XCSDPBAbilityScoreResponseBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBAbilityScoreResponse* resultAbilityScoreResponse;
}

- (XCSDPBAbilityScoreResponse*) defaultInstance;

- (XCSDPBAbilityScoreResponseBuilder*) clear;
- (XCSDPBAbilityScoreResponseBuilder*) clone;

- (XCSDPBAbilityScoreResponse*) build;
- (XCSDPBAbilityScoreResponse*) buildPartial;

- (XCSDPBAbilityScoreResponseBuilder*) mergeFrom:(XCSDPBAbilityScoreResponse*) other;
- (XCSDPBAbilityScoreResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBAbilityScoreResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTotalScore;
- (SInt32) totalScore;
- (XCSDPBAbilityScoreResponseBuilder*) setTotalScore:(SInt32) value;
- (XCSDPBAbilityScoreResponseBuilder*) clearTotalScore;

- (NSMutableArray *)gameList;
- (XCSDPBAbilityScoreResponseGameScore*)gameListAtIndex:(NSUInteger)index;
- (XCSDPBAbilityScoreResponseBuilder *)addGameList:(XCSDPBAbilityScoreResponseGameScore*)value;
- (XCSDPBAbilityScoreResponseBuilder *)setGameListArray:(NSArray *)array;
- (XCSDPBAbilityScoreResponseBuilder *)clearGameList;
@end


// @@protoc_insertion_point(global_scope)
