// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "XCSDHomework.pb.h"
// @@protoc_insertion_point(imports)

@class ObjectiveCFileOptions;
@class ObjectiveCFileOptionsBuilder;
@class PBDescriptorProto;
@class PBDescriptorProtoBuilder;
@class PBDescriptorProtoExtensionRange;
@class PBDescriptorProtoExtensionRangeBuilder;
@class PBEnumDescriptorProto;
@class PBEnumDescriptorProtoBuilder;
@class PBEnumOptions;
@class PBEnumOptionsBuilder;
@class PBEnumValueDescriptorProto;
@class PBEnumValueDescriptorProtoBuilder;
@class PBEnumValueOptions;
@class PBEnumValueOptionsBuilder;
@class PBFieldDescriptorProto;
@class PBFieldDescriptorProtoBuilder;
@class PBFieldOptions;
@class PBFieldOptionsBuilder;
@class PBFileDescriptorProto;
@class PBFileDescriptorProtoBuilder;
@class PBFileDescriptorSet;
@class PBFileDescriptorSetBuilder;
@class PBFileOptions;
@class PBFileOptionsBuilder;
@class PBMessageOptions;
@class PBMessageOptionsBuilder;
@class PBMethodDescriptorProto;
@class PBMethodDescriptorProtoBuilder;
@class PBMethodOptions;
@class PBMethodOptionsBuilder;
@class PBServiceDescriptorProto;
@class PBServiceDescriptorProtoBuilder;
@class PBServiceOptions;
@class PBServiceOptionsBuilder;
@class PBSourceCodeInfo;
@class PBSourceCodeInfoBuilder;
@class PBSourceCodeInfoLocation;
@class PBSourceCodeInfoLocationBuilder;
@class PBUninterpretedOption;
@class PBUninterpretedOptionBuilder;
@class PBUninterpretedOptionNamePart;
@class PBUninterpretedOptionNamePartBuilder;
@class XCSDPBAbilityValue;
@class XCSDPBAbilityValueBuilder;
@class XCSDPBClassAbilityRankingRequest;
@class XCSDPBClassAbilityRankingRequestBuilder;
@class XCSDPBClassAbilityRankingResponse;
@class XCSDPBClassAbilityRankingResponseBuilder;
@class XCSDPBClassHomework;
@class XCSDPBClassHomeworkBuilder;
@class XCSDPBDeleteHomeworkNoticeRequest;
@class XCSDPBDeleteHomeworkNoticeRequestBuilder;
@class XCSDPBDeleteHomeworkNoticeResponse;
@class XCSDPBDeleteHomeworkNoticeResponseBuilder;
@class XCSDPBGenerateHomeworkRequest;
@class XCSDPBGenerateHomeworkRequestBuilder;
@class XCSDPBGenerateHomeworkResponse;
@class XCSDPBGenerateHomeworkResponseBuilder;
@class XCSDPBGenerateHomeworkResponseUserHomework;
@class XCSDPBGenerateHomeworkResponseUserHomeworkBuilder;
@class XCSDPBHomework;
@class XCSDPBHomeworkBuilder;
@class XCSDPBHomeworkCalendarRequest;
@class XCSDPBHomeworkCalendarRequestBuilder;
@class XCSDPBHomeworkCalendarResponse;
@class XCSDPBHomeworkCalendarResponseBuilder;
@class XCSDPBHomeworkListRequest;
@class XCSDPBHomeworkListRequestBuilder;
@class XCSDPBHomeworkListResponse;
@class XCSDPBHomeworkListResponseBuilder;
@class XCSDPBHomeworkMember;
@class XCSDPBHomeworkMemberBuilder;
@class XCSDPBHomeworkMemberListRequest;
@class XCSDPBHomeworkMemberListRequestBuilder;
@class XCSDPBHomeworkMemberListResponse;
@class XCSDPBHomeworkMemberListResponseBuilder;
@class XCSDPBHomeworkRankingRequest;
@class XCSDPBHomeworkRankingRequestBuilder;
@class XCSDPBHomeworkRankingResponse;
@class XCSDPBHomeworkRankingResponseBuilder;
@class XCSDPBHomeworkRemainingCountRequest;
@class XCSDPBHomeworkRemainingCountRequestBuilder;
@class XCSDPBHomeworkRemainingCountResponse;
@class XCSDPBHomeworkRemainingCountResponseBuilder;
@class XCSDPBHomeworkSentListRequest;
@class XCSDPBHomeworkSentListRequestBuilder;
@class XCSDPBHomeworkSentListResponse;
@class XCSDPBHomeworkSentListResponseBuilder;
@class XCSDPBReadHomeworkNoticeRequest;
@class XCSDPBReadHomeworkNoticeRequestBuilder;
@class XCSDPBReadHomeworkNoticeResponse;
@class XCSDPBReadHomeworkNoticeResponseBuilder;
@class XCSDPBSendHomeworkRequest;
@class XCSDPBSendHomeworkRequestBuilder;
@class XCSDPBSendHomeworkResponse;
@class XCSDPBSendHomeworkResponseBuilder;
@class XCSDPBUserRank;
@class XCSDPBUserRankBuilder;


typedef NS_ENUM(SInt32, XCSDPBAbility) {
  XCSDPBAbilityAttention = 1,
  XCSDPBAbilityMemory = 2,
  XCSDPBAbilityReaction = 3,
  XCSDPBAbilityReasoning = 4,
  XCSDPBAbilitySpatialThinking = 5,
};

BOOL XCSDPBAbilityIsValidValue(XCSDPBAbility value);
NSString *NSStringFromXCSDPBAbility(XCSDPBAbility value);


@interface XCSDPBXcsdlearningAbilityRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define AbilityValue_ability @"ability"
#define AbilityValue_value @"value"
@interface XCSDPBAbilityValue : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasValue_:1;
  BOOL hasAbility_:1;
  SInt32 value;
  XCSDPBAbility ability;
}
- (BOOL) hasAbility;
- (BOOL) hasValue;
@property (readonly) XCSDPBAbility ability;
@property (readonly) SInt32 value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBAbilityValueBuilder*) builder;
+ (XCSDPBAbilityValueBuilder*) builder;
+ (XCSDPBAbilityValueBuilder*) builderWithPrototype:(XCSDPBAbilityValue*) prototype;
- (XCSDPBAbilityValueBuilder*) toBuilder;

+ (XCSDPBAbilityValue*) parseFromData:(NSData*) data;
+ (XCSDPBAbilityValue*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityValue*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBAbilityValue*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBAbilityValue*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBAbilityValue*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBAbilityValueBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBAbilityValue* resultAbilityValue;
}

- (XCSDPBAbilityValue*) defaultInstance;

- (XCSDPBAbilityValueBuilder*) clear;
- (XCSDPBAbilityValueBuilder*) clone;

- (XCSDPBAbilityValue*) build;
- (XCSDPBAbilityValue*) buildPartial;

- (XCSDPBAbilityValueBuilder*) mergeFrom:(XCSDPBAbilityValue*) other;
- (XCSDPBAbilityValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBAbilityValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAbility;
- (XCSDPBAbility) ability;
- (XCSDPBAbilityValueBuilder*) setAbility:(XCSDPBAbility) value;
- (XCSDPBAbilityValueBuilder*) clearAbility;

- (BOOL) hasValue;
- (SInt32) value;
- (XCSDPBAbilityValueBuilder*) setValue:(SInt32) value;
- (XCSDPBAbilityValueBuilder*) clearValue;
@end

#define ClassAbilityRankingRequest_classId @"classId"
@interface XCSDPBClassAbilityRankingRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasClassId_:1;
  SInt64 classId;
}
- (BOOL) hasClassId;
@property (readonly) SInt64 classId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBClassAbilityRankingRequestBuilder*) builder;
+ (XCSDPBClassAbilityRankingRequestBuilder*) builder;
+ (XCSDPBClassAbilityRankingRequestBuilder*) builderWithPrototype:(XCSDPBClassAbilityRankingRequest*) prototype;
- (XCSDPBClassAbilityRankingRequestBuilder*) toBuilder;

+ (XCSDPBClassAbilityRankingRequest*) parseFromData:(NSData*) data;
+ (XCSDPBClassAbilityRankingRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBClassAbilityRankingRequest*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBClassAbilityRankingRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBClassAbilityRankingRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBClassAbilityRankingRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBClassAbilityRankingRequestBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBClassAbilityRankingRequest* resultClassAbilityRankingRequest;
}

- (XCSDPBClassAbilityRankingRequest*) defaultInstance;

- (XCSDPBClassAbilityRankingRequestBuilder*) clear;
- (XCSDPBClassAbilityRankingRequestBuilder*) clone;

- (XCSDPBClassAbilityRankingRequest*) build;
- (XCSDPBClassAbilityRankingRequest*) buildPartial;

- (XCSDPBClassAbilityRankingRequestBuilder*) mergeFrom:(XCSDPBClassAbilityRankingRequest*) other;
- (XCSDPBClassAbilityRankingRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBClassAbilityRankingRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasClassId;
- (SInt64) classId;
- (XCSDPBClassAbilityRankingRequestBuilder*) setClassId:(SInt64) value;
- (XCSDPBClassAbilityRankingRequestBuilder*) clearClassId;
@end

#define ClassAbilityRankingResponse_rankList @"rankList"
@interface XCSDPBClassAbilityRankingResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * rankListArray;
}
@property (readonly, strong) NSArray * rankList;
- (XCSDPBUserRank*)rankListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBClassAbilityRankingResponseBuilder*) builder;
+ (XCSDPBClassAbilityRankingResponseBuilder*) builder;
+ (XCSDPBClassAbilityRankingResponseBuilder*) builderWithPrototype:(XCSDPBClassAbilityRankingResponse*) prototype;
- (XCSDPBClassAbilityRankingResponseBuilder*) toBuilder;

+ (XCSDPBClassAbilityRankingResponse*) parseFromData:(NSData*) data;
+ (XCSDPBClassAbilityRankingResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBClassAbilityRankingResponse*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBClassAbilityRankingResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBClassAbilityRankingResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBClassAbilityRankingResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBClassAbilityRankingResponseBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBClassAbilityRankingResponse* resultClassAbilityRankingResponse;
}

- (XCSDPBClassAbilityRankingResponse*) defaultInstance;

- (XCSDPBClassAbilityRankingResponseBuilder*) clear;
- (XCSDPBClassAbilityRankingResponseBuilder*) clone;

- (XCSDPBClassAbilityRankingResponse*) build;
- (XCSDPBClassAbilityRankingResponse*) buildPartial;

- (XCSDPBClassAbilityRankingResponseBuilder*) mergeFrom:(XCSDPBClassAbilityRankingResponse*) other;
- (XCSDPBClassAbilityRankingResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBClassAbilityRankingResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)rankList;
- (XCSDPBUserRank*)rankListAtIndex:(NSUInteger)index;
- (XCSDPBClassAbilityRankingResponseBuilder *)addRankList:(XCSDPBUserRank*)value;
- (XCSDPBClassAbilityRankingResponseBuilder *)setRankListArray:(NSArray *)array;
- (XCSDPBClassAbilityRankingResponseBuilder *)clearRankList;
@end


// @@protoc_insertion_point(global_scope)
