// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class ObjectiveCFileOptions;
@class ObjectiveCFileOptionsBuilder;
@class PBDescriptorProto;
@class PBDescriptorProtoBuilder;
@class PBDescriptorProtoExtensionRange;
@class PBDescriptorProtoExtensionRangeBuilder;
@class PBEnumDescriptorProto;
@class PBEnumDescriptorProtoBuilder;
@class PBEnumOptions;
@class PBEnumOptionsBuilder;
@class PBEnumValueDescriptorProto;
@class PBEnumValueDescriptorProtoBuilder;
@class PBEnumValueOptions;
@class PBEnumValueOptionsBuilder;
@class PBFieldDescriptorProto;
@class PBFieldDescriptorProtoBuilder;
@class PBFieldOptions;
@class PBFieldOptionsBuilder;
@class PBFileDescriptorProto;
@class PBFileDescriptorProtoBuilder;
@class PBFileDescriptorSet;
@class PBFileDescriptorSetBuilder;
@class PBFileOptions;
@class PBFileOptionsBuilder;
@class PBMessageOptions;
@class PBMessageOptionsBuilder;
@class PBMethodDescriptorProto;
@class PBMethodDescriptorProtoBuilder;
@class PBMethodOptions;
@class PBMethodOptionsBuilder;
@class PBServiceDescriptorProto;
@class PBServiceDescriptorProtoBuilder;
@class PBServiceOptions;
@class PBServiceOptionsBuilder;
@class PBSourceCodeInfo;
@class PBSourceCodeInfoBuilder;
@class PBSourceCodeInfoLocation;
@class PBSourceCodeInfoLocationBuilder;
@class PBUninterpretedOption;
@class PBUninterpretedOptionBuilder;
@class PBUninterpretedOptionNamePart;
@class PBUninterpretedOptionNamePartBuilder;
@class XCSDPBClassHomework;
@class XCSDPBClassHomeworkBuilder;
@class XCSDPBDeleteHomeworkNoticeRequest;
@class XCSDPBDeleteHomeworkNoticeRequestBuilder;
@class XCSDPBDeleteHomeworkNoticeResponse;
@class XCSDPBDeleteHomeworkNoticeResponseBuilder;
@class XCSDPBGenerateHomeworkRequest;
@class XCSDPBGenerateHomeworkRequestBuilder;
@class XCSDPBGenerateHomeworkResponse;
@class XCSDPBGenerateHomeworkResponseBuilder;
@class XCSDPBGenerateHomeworkResponseUserHomework;
@class XCSDPBGenerateHomeworkResponseUserHomeworkBuilder;
@class XCSDPBHomework;
@class XCSDPBHomeworkBuilder;
@class XCSDPBHomeworkCalendarRequest;
@class XCSDPBHomeworkCalendarRequestBuilder;
@class XCSDPBHomeworkCalendarResponse;
@class XCSDPBHomeworkCalendarResponseBuilder;
@class XCSDPBHomeworkListRequest;
@class XCSDPBHomeworkListRequestBuilder;
@class XCSDPBHomeworkListResponse;
@class XCSDPBHomeworkListResponseBuilder;
@class XCSDPBHomeworkMember;
@class XCSDPBHomeworkMemberBuilder;
@class XCSDPBHomeworkMemberListRequest;
@class XCSDPBHomeworkMemberListRequestBuilder;
@class XCSDPBHomeworkMemberListResponse;
@class XCSDPBHomeworkMemberListResponseBuilder;
@class XCSDPBHomeworkRankingRequest;
@class XCSDPBHomeworkRankingRequestBuilder;
@class XCSDPBHomeworkRankingResponse;
@class XCSDPBHomeworkRankingResponseBuilder;
@class XCSDPBHomeworkRemainingCountRequest;
@class XCSDPBHomeworkRemainingCountRequestBuilder;
@class XCSDPBHomeworkRemainingCountResponse;
@class XCSDPBHomeworkRemainingCountResponseBuilder;
@class XCSDPBHomeworkSentListRequest;
@class XCSDPBHomeworkSentListRequestBuilder;
@class XCSDPBHomeworkSentListResponse;
@class XCSDPBHomeworkSentListResponseBuilder;
@class XCSDPBReadHomeworkNoticeRequest;
@class XCSDPBReadHomeworkNoticeRequestBuilder;
@class XCSDPBReadHomeworkNoticeResponse;
@class XCSDPBReadHomeworkNoticeResponseBuilder;
@class XCSDPBSendHomeworkRequest;
@class XCSDPBSendHomeworkRequestBuilder;
@class XCSDPBSendHomeworkResponse;
@class XCSDPBSendHomeworkResponseBuilder;
@class XCSDPBUserRank;
@class XCSDPBUserRankBuilder;


typedef NS_ENUM(SInt32, XCSDPBHomeworkStatus) {
  XCSDPBHomeworkStatusUnfinished = 0,
  XCSDPBHomeworkStatusFinished = 1,
};

BOOL XCSDPBHomeworkStatusIsValidValue(XCSDPBHomeworkStatus value);
NSString *NSStringFromXCSDPBHomeworkStatus(XCSDPBHomeworkStatus value);

typedef NS_ENUM(SInt32, XCSDPBHomeworkType) {
  XCSDPBHomeworkTypeCustomized = 1,
  XCSDPBHomeworkTypeUnified = 2,
};

BOOL XCSDPBHomeworkTypeIsValidValue(XCSDPBHomeworkType value);
NSString *NSStringFromXCSDPBHomeworkType(XCSDPBHomeworkType value);

typedef NS_ENUM(SInt32, XCSDPBStudentScope) {
  XCSDPBStudentScopeAll = 1,
  XCSDPBStudentScopeNormal = 2,
  XCSDPBStudentScopeSpecial = 3,
};

BOOL XCSDPBStudentScopeIsValidValue(XCSDPBStudentScope value);
NSString *NSStringFromXCSDPBStudentScope(XCSDPBStudentScope value);


@interface XCSDPBXcsdhomeworkRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define Homework_id @"id"
#define Homework_memberId @"memberId"
#define Homework_title @"title"
#define Homework_sendUserId @"sendUserId"
#define Homework_senderName @"senderName"
#define Homework_senderAvatar @"senderAvatar"
#define Homework_targetName @"targetName"
#define Homework_status @"status"
#define Homework_hasRead @"hasRead"
#define Homework_sendTime @"sendTime"
@interface XCSDPBHomework : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasHasRead_:1;
  BOOL hasId_:1;
  BOOL hasMemberId_:1;
  BOOL hasSendUserId_:1;
  BOOL hasSendTime_:1;
  BOOL hasTitle_:1;
  BOOL hasSenderName_:1;
  BOOL hasSenderAvatar_:1;
  BOOL hasTargetName_:1;
  BOOL hasStatus_:1;
  BOOL hasRead_:1;
  SInt64 id;
  SInt64 memberId;
  SInt64 sendUserId;
  SInt64 sendTime;
  NSString* title;
  NSString* senderName;
  NSString* senderAvatar;
  NSString* targetName;
  XCSDPBHomeworkStatus status;
}
- (BOOL) hasId;
- (BOOL) hasMemberId;
- (BOOL) hasTitle;
- (BOOL) hasSendUserId;
- (BOOL) hasSenderName;
- (BOOL) hasSenderAvatar;
- (BOOL) hasTargetName;
- (BOOL) hasStatus;
- (BOOL) hasHasRead;
- (BOOL) hasSendTime;
@property (readonly) SInt64 id;
@property (readonly) SInt64 memberId;
@property (readonly, strong) NSString* title;
@property (readonly) SInt64 sendUserId;
@property (readonly, strong) NSString* senderName;
@property (readonly, strong) NSString* senderAvatar;
@property (readonly, strong) NSString* targetName;
@property (readonly) XCSDPBHomeworkStatus status;
- (BOOL) hasRead;
@property (readonly) SInt64 sendTime;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBHomeworkBuilder*) builder;
+ (XCSDPBHomeworkBuilder*) builder;
+ (XCSDPBHomeworkBuilder*) builderWithPrototype:(XCSDPBHomework*) prototype;
- (XCSDPBHomeworkBuilder*) toBuilder;

+ (XCSDPBHomework*) parseFromData:(NSData*) data;
+ (XCSDPBHomework*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomework*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBHomework*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomework*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBHomework*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBHomeworkBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBHomework* resultHomework;
}

- (XCSDPBHomework*) defaultInstance;

- (XCSDPBHomeworkBuilder*) clear;
- (XCSDPBHomeworkBuilder*) clone;

- (XCSDPBHomework*) build;
- (XCSDPBHomework*) buildPartial;

- (XCSDPBHomeworkBuilder*) mergeFrom:(XCSDPBHomework*) other;
- (XCSDPBHomeworkBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBHomeworkBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (XCSDPBHomeworkBuilder*) setId:(SInt64) value;
- (XCSDPBHomeworkBuilder*) clearId;

- (BOOL) hasMemberId;
- (SInt64) memberId;
- (XCSDPBHomeworkBuilder*) setMemberId:(SInt64) value;
- (XCSDPBHomeworkBuilder*) clearMemberId;

- (BOOL) hasTitle;
- (NSString*) title;
- (XCSDPBHomeworkBuilder*) setTitle:(NSString*) value;
- (XCSDPBHomeworkBuilder*) clearTitle;

- (BOOL) hasSendUserId;
- (SInt64) sendUserId;
- (XCSDPBHomeworkBuilder*) setSendUserId:(SInt64) value;
- (XCSDPBHomeworkBuilder*) clearSendUserId;

- (BOOL) hasSenderName;
- (NSString*) senderName;
- (XCSDPBHomeworkBuilder*) setSenderName:(NSString*) value;
- (XCSDPBHomeworkBuilder*) clearSenderName;

- (BOOL) hasSenderAvatar;
- (NSString*) senderAvatar;
- (XCSDPBHomeworkBuilder*) setSenderAvatar:(NSString*) value;
- (XCSDPBHomeworkBuilder*) clearSenderAvatar;

- (BOOL) hasTargetName;
- (NSString*) targetName;
- (XCSDPBHomeworkBuilder*) setTargetName:(NSString*) value;
- (XCSDPBHomeworkBuilder*) clearTargetName;

- (BOOL) hasStatus;
- (XCSDPBHomeworkStatus) status;
- (XCSDPBHomeworkBuilder*) setStatus:(XCSDPBHomeworkStatus) value;
- (XCSDPBHomeworkBuilder*) clearStatus;

- (BOOL) hasHasRead;
- (BOOL) hasRead;
- (XCSDPBHomeworkBuilder*) setHasRead:(BOOL) value;
- (XCSDPBHomeworkBuilder*) clearHasRead;

- (BOOL) hasSendTime;
- (SInt64) sendTime;
- (XCSDPBHomeworkBuilder*) setSendTime:(SInt64) value;
- (XCSDPBHomeworkBuilder*) clearSendTime;
@end

#define HomeworkListRequest_maxId @"maxId"
#define HomeworkListRequest_sinceId @"sinceId"
@interface XCSDPBHomeworkListRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMaxId_:1;
  BOOL hasSinceId_:1;
  SInt64 maxId;
  SInt64 sinceId;
}
- (BOOL) hasMaxId;
- (BOOL) hasSinceId;
@property (readonly) SInt64 maxId;
@property (readonly) SInt64 sinceId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBHomeworkListRequestBuilder*) builder;
+ (XCSDPBHomeworkListRequestBuilder*) builder;
+ (XCSDPBHomeworkListRequestBuilder*) builderWithPrototype:(XCSDPBHomeworkListRequest*) prototype;
- (XCSDPBHomeworkListRequestBuilder*) toBuilder;

+ (XCSDPBHomeworkListRequest*) parseFromData:(NSData*) data;
+ (XCSDPBHomeworkListRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkListRequest*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBHomeworkListRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkListRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBHomeworkListRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBHomeworkListRequestBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBHomeworkListRequest* resultHomeworkListRequest;
}

- (XCSDPBHomeworkListRequest*) defaultInstance;

- (XCSDPBHomeworkListRequestBuilder*) clear;
- (XCSDPBHomeworkListRequestBuilder*) clone;

- (XCSDPBHomeworkListRequest*) build;
- (XCSDPBHomeworkListRequest*) buildPartial;

- (XCSDPBHomeworkListRequestBuilder*) mergeFrom:(XCSDPBHomeworkListRequest*) other;
- (XCSDPBHomeworkListRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBHomeworkListRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMaxId;
- (SInt64) maxId;
- (XCSDPBHomeworkListRequestBuilder*) setMaxId:(SInt64) value;
- (XCSDPBHomeworkListRequestBuilder*) clearMaxId;

- (BOOL) hasSinceId;
- (SInt64) sinceId;
- (XCSDPBHomeworkListRequestBuilder*) setSinceId:(SInt64) value;
- (XCSDPBHomeworkListRequestBuilder*) clearSinceId;
@end

#define HomeworkListResponse_homeworks @"homeworks"
#define HomeworkListResponse_hasMore @"hasMore"
@interface XCSDPBHomeworkListResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasHasMore_:1;
  BOOL hasMore_:1;
  NSMutableArray * homeworksArray;
}
- (BOOL) hasHasMore;
@property (readonly, strong) NSArray * homeworks;
- (BOOL) hasMore;
- (XCSDPBHomework*)homeworksAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBHomeworkListResponseBuilder*) builder;
+ (XCSDPBHomeworkListResponseBuilder*) builder;
+ (XCSDPBHomeworkListResponseBuilder*) builderWithPrototype:(XCSDPBHomeworkListResponse*) prototype;
- (XCSDPBHomeworkListResponseBuilder*) toBuilder;

+ (XCSDPBHomeworkListResponse*) parseFromData:(NSData*) data;
+ (XCSDPBHomeworkListResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkListResponse*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBHomeworkListResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkListResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBHomeworkListResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBHomeworkListResponseBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBHomeworkListResponse* resultHomeworkListResponse;
}

- (XCSDPBHomeworkListResponse*) defaultInstance;

- (XCSDPBHomeworkListResponseBuilder*) clear;
- (XCSDPBHomeworkListResponseBuilder*) clone;

- (XCSDPBHomeworkListResponse*) build;
- (XCSDPBHomeworkListResponse*) buildPartial;

- (XCSDPBHomeworkListResponseBuilder*) mergeFrom:(XCSDPBHomeworkListResponse*) other;
- (XCSDPBHomeworkListResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBHomeworkListResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)homeworks;
- (XCSDPBHomework*)homeworksAtIndex:(NSUInteger)index;
- (XCSDPBHomeworkListResponseBuilder *)addHomeworks:(XCSDPBHomework*)value;
- (XCSDPBHomeworkListResponseBuilder *)setHomeworksArray:(NSArray *)array;
- (XCSDPBHomeworkListResponseBuilder *)clearHomeworks;

- (BOOL) hasHasMore;
- (BOOL) hasMore;
- (XCSDPBHomeworkListResponseBuilder*) setHasMore:(BOOL) value;
- (XCSDPBHomeworkListResponseBuilder*) clearHasMore;
@end

#define ReadHomeworkNoticeRequest_homeworkNoticeId @"homeworkNoticeId"
@interface XCSDPBReadHomeworkNoticeRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasHomeworkNoticeId_:1;
  SInt64 homeworkNoticeId;
}
- (BOOL) hasHomeworkNoticeId;
@property (readonly) SInt64 homeworkNoticeId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBReadHomeworkNoticeRequestBuilder*) builder;
+ (XCSDPBReadHomeworkNoticeRequestBuilder*) builder;
+ (XCSDPBReadHomeworkNoticeRequestBuilder*) builderWithPrototype:(XCSDPBReadHomeworkNoticeRequest*) prototype;
- (XCSDPBReadHomeworkNoticeRequestBuilder*) toBuilder;

+ (XCSDPBReadHomeworkNoticeRequest*) parseFromData:(NSData*) data;
+ (XCSDPBReadHomeworkNoticeRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBReadHomeworkNoticeRequest*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBReadHomeworkNoticeRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBReadHomeworkNoticeRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBReadHomeworkNoticeRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBReadHomeworkNoticeRequestBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBReadHomeworkNoticeRequest* resultReadHomeworkNoticeRequest;
}

- (XCSDPBReadHomeworkNoticeRequest*) defaultInstance;

- (XCSDPBReadHomeworkNoticeRequestBuilder*) clear;
- (XCSDPBReadHomeworkNoticeRequestBuilder*) clone;

- (XCSDPBReadHomeworkNoticeRequest*) build;
- (XCSDPBReadHomeworkNoticeRequest*) buildPartial;

- (XCSDPBReadHomeworkNoticeRequestBuilder*) mergeFrom:(XCSDPBReadHomeworkNoticeRequest*) other;
- (XCSDPBReadHomeworkNoticeRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBReadHomeworkNoticeRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasHomeworkNoticeId;
- (SInt64) homeworkNoticeId;
- (XCSDPBReadHomeworkNoticeRequestBuilder*) setHomeworkNoticeId:(SInt64) value;
- (XCSDPBReadHomeworkNoticeRequestBuilder*) clearHomeworkNoticeId;
@end

@interface XCSDPBReadHomeworkNoticeResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBReadHomeworkNoticeResponseBuilder*) builder;
+ (XCSDPBReadHomeworkNoticeResponseBuilder*) builder;
+ (XCSDPBReadHomeworkNoticeResponseBuilder*) builderWithPrototype:(XCSDPBReadHomeworkNoticeResponse*) prototype;
- (XCSDPBReadHomeworkNoticeResponseBuilder*) toBuilder;

+ (XCSDPBReadHomeworkNoticeResponse*) parseFromData:(NSData*) data;
+ (XCSDPBReadHomeworkNoticeResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBReadHomeworkNoticeResponse*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBReadHomeworkNoticeResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBReadHomeworkNoticeResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBReadHomeworkNoticeResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBReadHomeworkNoticeResponseBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBReadHomeworkNoticeResponse* resultReadHomeworkNoticeResponse;
}

- (XCSDPBReadHomeworkNoticeResponse*) defaultInstance;

- (XCSDPBReadHomeworkNoticeResponseBuilder*) clear;
- (XCSDPBReadHomeworkNoticeResponseBuilder*) clone;

- (XCSDPBReadHomeworkNoticeResponse*) build;
- (XCSDPBReadHomeworkNoticeResponse*) buildPartial;

- (XCSDPBReadHomeworkNoticeResponseBuilder*) mergeFrom:(XCSDPBReadHomeworkNoticeResponse*) other;
- (XCSDPBReadHomeworkNoticeResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBReadHomeworkNoticeResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define DeleteHomeworkNoticeRequest_homeworkNoticeId @"homeworkNoticeId"
@interface XCSDPBDeleteHomeworkNoticeRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasHomeworkNoticeId_:1;
  SInt64 homeworkNoticeId;
}
- (BOOL) hasHomeworkNoticeId;
@property (readonly) SInt64 homeworkNoticeId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBDeleteHomeworkNoticeRequestBuilder*) builder;
+ (XCSDPBDeleteHomeworkNoticeRequestBuilder*) builder;
+ (XCSDPBDeleteHomeworkNoticeRequestBuilder*) builderWithPrototype:(XCSDPBDeleteHomeworkNoticeRequest*) prototype;
- (XCSDPBDeleteHomeworkNoticeRequestBuilder*) toBuilder;

+ (XCSDPBDeleteHomeworkNoticeRequest*) parseFromData:(NSData*) data;
+ (XCSDPBDeleteHomeworkNoticeRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBDeleteHomeworkNoticeRequest*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBDeleteHomeworkNoticeRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBDeleteHomeworkNoticeRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBDeleteHomeworkNoticeRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBDeleteHomeworkNoticeRequestBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBDeleteHomeworkNoticeRequest* resultDeleteHomeworkNoticeRequest;
}

- (XCSDPBDeleteHomeworkNoticeRequest*) defaultInstance;

- (XCSDPBDeleteHomeworkNoticeRequestBuilder*) clear;
- (XCSDPBDeleteHomeworkNoticeRequestBuilder*) clone;

- (XCSDPBDeleteHomeworkNoticeRequest*) build;
- (XCSDPBDeleteHomeworkNoticeRequest*) buildPartial;

- (XCSDPBDeleteHomeworkNoticeRequestBuilder*) mergeFrom:(XCSDPBDeleteHomeworkNoticeRequest*) other;
- (XCSDPBDeleteHomeworkNoticeRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBDeleteHomeworkNoticeRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasHomeworkNoticeId;
- (SInt64) homeworkNoticeId;
- (XCSDPBDeleteHomeworkNoticeRequestBuilder*) setHomeworkNoticeId:(SInt64) value;
- (XCSDPBDeleteHomeworkNoticeRequestBuilder*) clearHomeworkNoticeId;
@end

@interface XCSDPBDeleteHomeworkNoticeResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBDeleteHomeworkNoticeResponseBuilder*) builder;
+ (XCSDPBDeleteHomeworkNoticeResponseBuilder*) builder;
+ (XCSDPBDeleteHomeworkNoticeResponseBuilder*) builderWithPrototype:(XCSDPBDeleteHomeworkNoticeResponse*) prototype;
- (XCSDPBDeleteHomeworkNoticeResponseBuilder*) toBuilder;

+ (XCSDPBDeleteHomeworkNoticeResponse*) parseFromData:(NSData*) data;
+ (XCSDPBDeleteHomeworkNoticeResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBDeleteHomeworkNoticeResponse*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBDeleteHomeworkNoticeResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBDeleteHomeworkNoticeResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBDeleteHomeworkNoticeResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBDeleteHomeworkNoticeResponseBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBDeleteHomeworkNoticeResponse* resultDeleteHomeworkNoticeResponse;
}

- (XCSDPBDeleteHomeworkNoticeResponse*) defaultInstance;

- (XCSDPBDeleteHomeworkNoticeResponseBuilder*) clear;
- (XCSDPBDeleteHomeworkNoticeResponseBuilder*) clone;

- (XCSDPBDeleteHomeworkNoticeResponse*) build;
- (XCSDPBDeleteHomeworkNoticeResponse*) buildPartial;

- (XCSDPBDeleteHomeworkNoticeResponseBuilder*) mergeFrom:(XCSDPBDeleteHomeworkNoticeResponse*) other;
- (XCSDPBDeleteHomeworkNoticeResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBDeleteHomeworkNoticeResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define HomeworkRankingRequest_childUserId @"childUserId"
#define HomeworkRankingRequest_classId @"classId"
@interface XCSDPBHomeworkRankingRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChildUserId_:1;
  BOOL hasClassId_:1;
  SInt64 childUserId;
  SInt64 classId;
}
- (BOOL) hasChildUserId;
- (BOOL) hasClassId;
@property (readonly) SInt64 childUserId;
@property (readonly) SInt64 classId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBHomeworkRankingRequestBuilder*) builder;
+ (XCSDPBHomeworkRankingRequestBuilder*) builder;
+ (XCSDPBHomeworkRankingRequestBuilder*) builderWithPrototype:(XCSDPBHomeworkRankingRequest*) prototype;
- (XCSDPBHomeworkRankingRequestBuilder*) toBuilder;

+ (XCSDPBHomeworkRankingRequest*) parseFromData:(NSData*) data;
+ (XCSDPBHomeworkRankingRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkRankingRequest*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBHomeworkRankingRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkRankingRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBHomeworkRankingRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBHomeworkRankingRequestBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBHomeworkRankingRequest* resultHomeworkRankingRequest;
}

- (XCSDPBHomeworkRankingRequest*) defaultInstance;

- (XCSDPBHomeworkRankingRequestBuilder*) clear;
- (XCSDPBHomeworkRankingRequestBuilder*) clone;

- (XCSDPBHomeworkRankingRequest*) build;
- (XCSDPBHomeworkRankingRequest*) buildPartial;

- (XCSDPBHomeworkRankingRequestBuilder*) mergeFrom:(XCSDPBHomeworkRankingRequest*) other;
- (XCSDPBHomeworkRankingRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBHomeworkRankingRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChildUserId;
- (SInt64) childUserId;
- (XCSDPBHomeworkRankingRequestBuilder*) setChildUserId:(SInt64) value;
- (XCSDPBHomeworkRankingRequestBuilder*) clearChildUserId;

- (BOOL) hasClassId;
- (SInt64) classId;
- (XCSDPBHomeworkRankingRequestBuilder*) setClassId:(SInt64) value;
- (XCSDPBHomeworkRankingRequestBuilder*) clearClassId;
@end

#define UserRank_rank @"rank"
#define UserRank_userId @"userId"
#define UserRank_name @"name"
#define UserRank_avatar @"avatar"
#define UserRank_score @"score"
@interface XCSDPBUserRank : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasRank_:1;
  BOOL hasScore_:1;
  BOOL hasName_:1;
  BOOL hasAvatar_:1;
  SInt64 userId;
  SInt32 rank;
  SInt32 score;
  NSString* name;
  NSString* avatar;
}
- (BOOL) hasRank;
- (BOOL) hasUserId;
- (BOOL) hasName;
- (BOOL) hasAvatar;
- (BOOL) hasScore;
@property (readonly) SInt32 rank;
@property (readonly) SInt64 userId;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* avatar;
@property (readonly) SInt32 score;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBUserRankBuilder*) builder;
+ (XCSDPBUserRankBuilder*) builder;
+ (XCSDPBUserRankBuilder*) builderWithPrototype:(XCSDPBUserRank*) prototype;
- (XCSDPBUserRankBuilder*) toBuilder;

+ (XCSDPBUserRank*) parseFromData:(NSData*) data;
+ (XCSDPBUserRank*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBUserRank*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBUserRank*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBUserRank*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBUserRank*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBUserRankBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBUserRank* resultUserRank;
}

- (XCSDPBUserRank*) defaultInstance;

- (XCSDPBUserRankBuilder*) clear;
- (XCSDPBUserRankBuilder*) clone;

- (XCSDPBUserRank*) build;
- (XCSDPBUserRank*) buildPartial;

- (XCSDPBUserRankBuilder*) mergeFrom:(XCSDPBUserRank*) other;
- (XCSDPBUserRankBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBUserRankBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRank;
- (SInt32) rank;
- (XCSDPBUserRankBuilder*) setRank:(SInt32) value;
- (XCSDPBUserRankBuilder*) clearRank;

- (BOOL) hasUserId;
- (SInt64) userId;
- (XCSDPBUserRankBuilder*) setUserId:(SInt64) value;
- (XCSDPBUserRankBuilder*) clearUserId;

- (BOOL) hasName;
- (NSString*) name;
- (XCSDPBUserRankBuilder*) setName:(NSString*) value;
- (XCSDPBUserRankBuilder*) clearName;

- (BOOL) hasAvatar;
- (NSString*) avatar;
- (XCSDPBUserRankBuilder*) setAvatar:(NSString*) value;
- (XCSDPBUserRankBuilder*) clearAvatar;

- (BOOL) hasScore;
- (SInt32) score;
- (XCSDPBUserRankBuilder*) setScore:(SInt32) value;
- (XCSDPBUserRankBuilder*) clearScore;
@end

#define HomeworkRankingResponse_rankList @"rankList"
@interface XCSDPBHomeworkRankingResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * rankListArray;
}
@property (readonly, strong) NSArray * rankList;
- (XCSDPBUserRank*)rankListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBHomeworkRankingResponseBuilder*) builder;
+ (XCSDPBHomeworkRankingResponseBuilder*) builder;
+ (XCSDPBHomeworkRankingResponseBuilder*) builderWithPrototype:(XCSDPBHomeworkRankingResponse*) prototype;
- (XCSDPBHomeworkRankingResponseBuilder*) toBuilder;

+ (XCSDPBHomeworkRankingResponse*) parseFromData:(NSData*) data;
+ (XCSDPBHomeworkRankingResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkRankingResponse*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBHomeworkRankingResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkRankingResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBHomeworkRankingResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBHomeworkRankingResponseBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBHomeworkRankingResponse* resultHomeworkRankingResponse;
}

- (XCSDPBHomeworkRankingResponse*) defaultInstance;

- (XCSDPBHomeworkRankingResponseBuilder*) clear;
- (XCSDPBHomeworkRankingResponseBuilder*) clone;

- (XCSDPBHomeworkRankingResponse*) build;
- (XCSDPBHomeworkRankingResponse*) buildPartial;

- (XCSDPBHomeworkRankingResponseBuilder*) mergeFrom:(XCSDPBHomeworkRankingResponse*) other;
- (XCSDPBHomeworkRankingResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBHomeworkRankingResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)rankList;
- (XCSDPBUserRank*)rankListAtIndex:(NSUInteger)index;
- (XCSDPBHomeworkRankingResponseBuilder *)addRankList:(XCSDPBUserRank*)value;
- (XCSDPBHomeworkRankingResponseBuilder *)setRankListArray:(NSArray *)array;
- (XCSDPBHomeworkRankingResponseBuilder *)clearRankList;
@end

#define HomeworkCalendarRequest_childUserId @"childUserId"
@interface XCSDPBHomeworkCalendarRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChildUserId_:1;
  SInt64 childUserId;
}
- (BOOL) hasChildUserId;
@property (readonly) SInt64 childUserId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBHomeworkCalendarRequestBuilder*) builder;
+ (XCSDPBHomeworkCalendarRequestBuilder*) builder;
+ (XCSDPBHomeworkCalendarRequestBuilder*) builderWithPrototype:(XCSDPBHomeworkCalendarRequest*) prototype;
- (XCSDPBHomeworkCalendarRequestBuilder*) toBuilder;

+ (XCSDPBHomeworkCalendarRequest*) parseFromData:(NSData*) data;
+ (XCSDPBHomeworkCalendarRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkCalendarRequest*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBHomeworkCalendarRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkCalendarRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBHomeworkCalendarRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBHomeworkCalendarRequestBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBHomeworkCalendarRequest* resultHomeworkCalendarRequest;
}

- (XCSDPBHomeworkCalendarRequest*) defaultInstance;

- (XCSDPBHomeworkCalendarRequestBuilder*) clear;
- (XCSDPBHomeworkCalendarRequestBuilder*) clone;

- (XCSDPBHomeworkCalendarRequest*) build;
- (XCSDPBHomeworkCalendarRequest*) buildPartial;

- (XCSDPBHomeworkCalendarRequestBuilder*) mergeFrom:(XCSDPBHomeworkCalendarRequest*) other;
- (XCSDPBHomeworkCalendarRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBHomeworkCalendarRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChildUserId;
- (SInt64) childUserId;
- (XCSDPBHomeworkCalendarRequestBuilder*) setChildUserId:(SInt64) value;
- (XCSDPBHomeworkCalendarRequestBuilder*) clearChildUserId;
@end

#define HomeworkCalendarResponse_unfinished @"unfinished"
#define HomeworkCalendarResponse_finished @"finished"
@interface XCSDPBHomeworkCalendarResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  PBAppendableArray * unfinishedArray;
  PBAppendableArray * finishedArray;
}
@property (readonly, strong) PBArray * unfinished;
@property (readonly, strong) PBArray * finished;
- (SInt32)unfinishedAtIndex:(NSUInteger)index;
- (SInt32)finishedAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBHomeworkCalendarResponseBuilder*) builder;
+ (XCSDPBHomeworkCalendarResponseBuilder*) builder;
+ (XCSDPBHomeworkCalendarResponseBuilder*) builderWithPrototype:(XCSDPBHomeworkCalendarResponse*) prototype;
- (XCSDPBHomeworkCalendarResponseBuilder*) toBuilder;

+ (XCSDPBHomeworkCalendarResponse*) parseFromData:(NSData*) data;
+ (XCSDPBHomeworkCalendarResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkCalendarResponse*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBHomeworkCalendarResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkCalendarResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBHomeworkCalendarResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBHomeworkCalendarResponseBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBHomeworkCalendarResponse* resultHomeworkCalendarResponse;
}

- (XCSDPBHomeworkCalendarResponse*) defaultInstance;

- (XCSDPBHomeworkCalendarResponseBuilder*) clear;
- (XCSDPBHomeworkCalendarResponseBuilder*) clone;

- (XCSDPBHomeworkCalendarResponse*) build;
- (XCSDPBHomeworkCalendarResponse*) buildPartial;

- (XCSDPBHomeworkCalendarResponseBuilder*) mergeFrom:(XCSDPBHomeworkCalendarResponse*) other;
- (XCSDPBHomeworkCalendarResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBHomeworkCalendarResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)unfinished;
- (SInt32)unfinishedAtIndex:(NSUInteger)index;
- (XCSDPBHomeworkCalendarResponseBuilder *)addUnfinished:(SInt32)value;
- (XCSDPBHomeworkCalendarResponseBuilder *)setUnfinishedArray:(NSArray *)array;
- (XCSDPBHomeworkCalendarResponseBuilder *)setUnfinishedValues:(const SInt32 *)values count:(NSUInteger)count;
- (XCSDPBHomeworkCalendarResponseBuilder *)clearUnfinished;

- (PBAppendableArray *)finished;
- (SInt32)finishedAtIndex:(NSUInteger)index;
- (XCSDPBHomeworkCalendarResponseBuilder *)addFinished:(SInt32)value;
- (XCSDPBHomeworkCalendarResponseBuilder *)setFinishedArray:(NSArray *)array;
- (XCSDPBHomeworkCalendarResponseBuilder *)setFinishedValues:(const SInt32 *)values count:(NSUInteger)count;
- (XCSDPBHomeworkCalendarResponseBuilder *)clearFinished;
@end

#define ClassHomework_homeworkId @"homeworkId"
#define ClassHomework_className @"className"
#define ClassHomework_title @"title"
#define ClassHomework_type @"type"
#define ClassHomework_sendTime @"sendTime"
#define ClassHomework_finishedCount @"finishedCount"
#define ClassHomework_totalCount @"totalCount"
@interface XCSDPBClassHomework : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasHomeworkId_:1;
  BOOL hasSendTime_:1;
  BOOL hasFinishedCount_:1;
  BOOL hasTotalCount_:1;
  BOOL hasClassName_:1;
  BOOL hasTitle_:1;
  BOOL hasType_:1;
  SInt64 homeworkId;
  SInt64 sendTime;
  SInt32 finishedCount;
  SInt32 totalCount;
  NSString* className;
  NSString* title;
  XCSDPBHomeworkType type;
}
- (BOOL) hasHomeworkId;
- (BOOL) hasClassName;
- (BOOL) hasTitle;
- (BOOL) hasType;
- (BOOL) hasSendTime;
- (BOOL) hasFinishedCount;
- (BOOL) hasTotalCount;
@property (readonly) SInt64 homeworkId;
@property (readonly, strong) NSString* className;
@property (readonly, strong) NSString* title;
@property (readonly) XCSDPBHomeworkType type;
@property (readonly) SInt64 sendTime;
@property (readonly) SInt32 finishedCount;
@property (readonly) SInt32 totalCount;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBClassHomeworkBuilder*) builder;
+ (XCSDPBClassHomeworkBuilder*) builder;
+ (XCSDPBClassHomeworkBuilder*) builderWithPrototype:(XCSDPBClassHomework*) prototype;
- (XCSDPBClassHomeworkBuilder*) toBuilder;

+ (XCSDPBClassHomework*) parseFromData:(NSData*) data;
+ (XCSDPBClassHomework*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBClassHomework*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBClassHomework*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBClassHomework*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBClassHomework*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBClassHomeworkBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBClassHomework* resultClassHomework;
}

- (XCSDPBClassHomework*) defaultInstance;

- (XCSDPBClassHomeworkBuilder*) clear;
- (XCSDPBClassHomeworkBuilder*) clone;

- (XCSDPBClassHomework*) build;
- (XCSDPBClassHomework*) buildPartial;

- (XCSDPBClassHomeworkBuilder*) mergeFrom:(XCSDPBClassHomework*) other;
- (XCSDPBClassHomeworkBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBClassHomeworkBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasHomeworkId;
- (SInt64) homeworkId;
- (XCSDPBClassHomeworkBuilder*) setHomeworkId:(SInt64) value;
- (XCSDPBClassHomeworkBuilder*) clearHomeworkId;

- (BOOL) hasClassName;
- (NSString*) className;
- (XCSDPBClassHomeworkBuilder*) setClassName:(NSString*) value;
- (XCSDPBClassHomeworkBuilder*) clearClassName;

- (BOOL) hasTitle;
- (NSString*) title;
- (XCSDPBClassHomeworkBuilder*) setTitle:(NSString*) value;
- (XCSDPBClassHomeworkBuilder*) clearTitle;

- (BOOL) hasType;
- (XCSDPBHomeworkType) type;
- (XCSDPBClassHomeworkBuilder*) setType:(XCSDPBHomeworkType) value;
- (XCSDPBClassHomeworkBuilder*) clearType;

- (BOOL) hasSendTime;
- (SInt64) sendTime;
- (XCSDPBClassHomeworkBuilder*) setSendTime:(SInt64) value;
- (XCSDPBClassHomeworkBuilder*) clearSendTime;

- (BOOL) hasFinishedCount;
- (SInt32) finishedCount;
- (XCSDPBClassHomeworkBuilder*) setFinishedCount:(SInt32) value;
- (XCSDPBClassHomeworkBuilder*) clearFinishedCount;

- (BOOL) hasTotalCount;
- (SInt32) totalCount;
- (XCSDPBClassHomeworkBuilder*) setTotalCount:(SInt32) value;
- (XCSDPBClassHomeworkBuilder*) clearTotalCount;
@end

#define HomeworkSentListRequest_maxId @"maxId"
#define HomeworkSentListRequest_sinceId @"sinceId"
@interface XCSDPBHomeworkSentListRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMaxId_:1;
  BOOL hasSinceId_:1;
  SInt64 maxId;
  SInt64 sinceId;
}
- (BOOL) hasMaxId;
- (BOOL) hasSinceId;
@property (readonly) SInt64 maxId;
@property (readonly) SInt64 sinceId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBHomeworkSentListRequestBuilder*) builder;
+ (XCSDPBHomeworkSentListRequestBuilder*) builder;
+ (XCSDPBHomeworkSentListRequestBuilder*) builderWithPrototype:(XCSDPBHomeworkSentListRequest*) prototype;
- (XCSDPBHomeworkSentListRequestBuilder*) toBuilder;

+ (XCSDPBHomeworkSentListRequest*) parseFromData:(NSData*) data;
+ (XCSDPBHomeworkSentListRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkSentListRequest*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBHomeworkSentListRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkSentListRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBHomeworkSentListRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBHomeworkSentListRequestBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBHomeworkSentListRequest* resultHomeworkSentListRequest;
}

- (XCSDPBHomeworkSentListRequest*) defaultInstance;

- (XCSDPBHomeworkSentListRequestBuilder*) clear;
- (XCSDPBHomeworkSentListRequestBuilder*) clone;

- (XCSDPBHomeworkSentListRequest*) build;
- (XCSDPBHomeworkSentListRequest*) buildPartial;

- (XCSDPBHomeworkSentListRequestBuilder*) mergeFrom:(XCSDPBHomeworkSentListRequest*) other;
- (XCSDPBHomeworkSentListRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBHomeworkSentListRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMaxId;
- (SInt64) maxId;
- (XCSDPBHomeworkSentListRequestBuilder*) setMaxId:(SInt64) value;
- (XCSDPBHomeworkSentListRequestBuilder*) clearMaxId;

- (BOOL) hasSinceId;
- (SInt64) sinceId;
- (XCSDPBHomeworkSentListRequestBuilder*) setSinceId:(SInt64) value;
- (XCSDPBHomeworkSentListRequestBuilder*) clearSinceId;
@end

#define HomeworkSentListResponse_homeworks @"homeworks"
#define HomeworkSentListResponse_hasMore @"hasMore"
@interface XCSDPBHomeworkSentListResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasHasMore_:1;
  BOOL hasMore_:1;
  NSMutableArray * homeworksArray;
}
- (BOOL) hasHasMore;
@property (readonly, strong) NSArray * homeworks;
- (BOOL) hasMore;
- (XCSDPBClassHomework*)homeworksAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBHomeworkSentListResponseBuilder*) builder;
+ (XCSDPBHomeworkSentListResponseBuilder*) builder;
+ (XCSDPBHomeworkSentListResponseBuilder*) builderWithPrototype:(XCSDPBHomeworkSentListResponse*) prototype;
- (XCSDPBHomeworkSentListResponseBuilder*) toBuilder;

+ (XCSDPBHomeworkSentListResponse*) parseFromData:(NSData*) data;
+ (XCSDPBHomeworkSentListResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkSentListResponse*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBHomeworkSentListResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkSentListResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBHomeworkSentListResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBHomeworkSentListResponseBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBHomeworkSentListResponse* resultHomeworkSentListResponse;
}

- (XCSDPBHomeworkSentListResponse*) defaultInstance;

- (XCSDPBHomeworkSentListResponseBuilder*) clear;
- (XCSDPBHomeworkSentListResponseBuilder*) clone;

- (XCSDPBHomeworkSentListResponse*) build;
- (XCSDPBHomeworkSentListResponse*) buildPartial;

- (XCSDPBHomeworkSentListResponseBuilder*) mergeFrom:(XCSDPBHomeworkSentListResponse*) other;
- (XCSDPBHomeworkSentListResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBHomeworkSentListResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)homeworks;
- (XCSDPBClassHomework*)homeworksAtIndex:(NSUInteger)index;
- (XCSDPBHomeworkSentListResponseBuilder *)addHomeworks:(XCSDPBClassHomework*)value;
- (XCSDPBHomeworkSentListResponseBuilder *)setHomeworksArray:(NSArray *)array;
- (XCSDPBHomeworkSentListResponseBuilder *)clearHomeworks;

- (BOOL) hasHasMore;
- (BOOL) hasMore;
- (XCSDPBHomeworkSentListResponseBuilder*) setHasMore:(BOOL) value;
- (XCSDPBHomeworkSentListResponseBuilder*) clearHasMore;
@end

#define HomeworkMember_memberId @"memberId"
#define HomeworkMember_name @"name"
#define HomeworkMember_avatar @"avatar"
#define HomeworkMember_status @"status"
#define HomeworkMember_score @"score"
#define HomeworkMember_specialAttention @"specialAttention"
@interface XCSDPBHomeworkMember : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSpecialAttention_:1;
  BOOL hasMemberId_:1;
  BOOL hasScore_:1;
  BOOL hasName_:1;
  BOOL hasAvatar_:1;
  BOOL hasStatus_:1;
  BOOL specialAttention_:1;
  SInt64 memberId;
  SInt32 score;
  NSString* name;
  NSString* avatar;
  XCSDPBHomeworkStatus status;
}
- (BOOL) hasMemberId;
- (BOOL) hasName;
- (BOOL) hasAvatar;
- (BOOL) hasStatus;
- (BOOL) hasScore;
- (BOOL) hasSpecialAttention;
@property (readonly) SInt64 memberId;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* avatar;
@property (readonly) XCSDPBHomeworkStatus status;
@property (readonly) SInt32 score;
- (BOOL) specialAttention;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBHomeworkMemberBuilder*) builder;
+ (XCSDPBHomeworkMemberBuilder*) builder;
+ (XCSDPBHomeworkMemberBuilder*) builderWithPrototype:(XCSDPBHomeworkMember*) prototype;
- (XCSDPBHomeworkMemberBuilder*) toBuilder;

+ (XCSDPBHomeworkMember*) parseFromData:(NSData*) data;
+ (XCSDPBHomeworkMember*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkMember*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBHomeworkMember*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkMember*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBHomeworkMember*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBHomeworkMemberBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBHomeworkMember* resultHomeworkMember;
}

- (XCSDPBHomeworkMember*) defaultInstance;

- (XCSDPBHomeworkMemberBuilder*) clear;
- (XCSDPBHomeworkMemberBuilder*) clone;

- (XCSDPBHomeworkMember*) build;
- (XCSDPBHomeworkMember*) buildPartial;

- (XCSDPBHomeworkMemberBuilder*) mergeFrom:(XCSDPBHomeworkMember*) other;
- (XCSDPBHomeworkMemberBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBHomeworkMemberBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMemberId;
- (SInt64) memberId;
- (XCSDPBHomeworkMemberBuilder*) setMemberId:(SInt64) value;
- (XCSDPBHomeworkMemberBuilder*) clearMemberId;

- (BOOL) hasName;
- (NSString*) name;
- (XCSDPBHomeworkMemberBuilder*) setName:(NSString*) value;
- (XCSDPBHomeworkMemberBuilder*) clearName;

- (BOOL) hasAvatar;
- (NSString*) avatar;
- (XCSDPBHomeworkMemberBuilder*) setAvatar:(NSString*) value;
- (XCSDPBHomeworkMemberBuilder*) clearAvatar;

- (BOOL) hasStatus;
- (XCSDPBHomeworkStatus) status;
- (XCSDPBHomeworkMemberBuilder*) setStatus:(XCSDPBHomeworkStatus) value;
- (XCSDPBHomeworkMemberBuilder*) clearStatus;

- (BOOL) hasScore;
- (SInt32) score;
- (XCSDPBHomeworkMemberBuilder*) setScore:(SInt32) value;
- (XCSDPBHomeworkMemberBuilder*) clearScore;

- (BOOL) hasSpecialAttention;
- (BOOL) specialAttention;
- (XCSDPBHomeworkMemberBuilder*) setSpecialAttention:(BOOL) value;
- (XCSDPBHomeworkMemberBuilder*) clearSpecialAttention;
@end

#define HomeworkMemberListRequest_homeworkId @"homeworkId"
#define HomeworkMemberListRequest_pageNum @"pageNum"
@interface XCSDPBHomeworkMemberListRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasHomeworkId_:1;
  BOOL hasPageNum_:1;
  SInt64 homeworkId;
  SInt32 pageNum;
}
- (BOOL) hasHomeworkId;
- (BOOL) hasPageNum;
@property (readonly) SInt64 homeworkId;
@property (readonly) SInt32 pageNum;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBHomeworkMemberListRequestBuilder*) builder;
+ (XCSDPBHomeworkMemberListRequestBuilder*) builder;
+ (XCSDPBHomeworkMemberListRequestBuilder*) builderWithPrototype:(XCSDPBHomeworkMemberListRequest*) prototype;
- (XCSDPBHomeworkMemberListRequestBuilder*) toBuilder;

+ (XCSDPBHomeworkMemberListRequest*) parseFromData:(NSData*) data;
+ (XCSDPBHomeworkMemberListRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkMemberListRequest*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBHomeworkMemberListRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkMemberListRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBHomeworkMemberListRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBHomeworkMemberListRequestBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBHomeworkMemberListRequest* resultHomeworkMemberListRequest;
}

- (XCSDPBHomeworkMemberListRequest*) defaultInstance;

- (XCSDPBHomeworkMemberListRequestBuilder*) clear;
- (XCSDPBHomeworkMemberListRequestBuilder*) clone;

- (XCSDPBHomeworkMemberListRequest*) build;
- (XCSDPBHomeworkMemberListRequest*) buildPartial;

- (XCSDPBHomeworkMemberListRequestBuilder*) mergeFrom:(XCSDPBHomeworkMemberListRequest*) other;
- (XCSDPBHomeworkMemberListRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBHomeworkMemberListRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasHomeworkId;
- (SInt64) homeworkId;
- (XCSDPBHomeworkMemberListRequestBuilder*) setHomeworkId:(SInt64) value;
- (XCSDPBHomeworkMemberListRequestBuilder*) clearHomeworkId;

- (BOOL) hasPageNum;
- (SInt32) pageNum;
- (XCSDPBHomeworkMemberListRequestBuilder*) setPageNum:(SInt32) value;
- (XCSDPBHomeworkMemberListRequestBuilder*) clearPageNum;
@end

#define HomeworkMemberListResponse_members @"members"
#define HomeworkMemberListResponse_hasMore @"hasMore"
@interface XCSDPBHomeworkMemberListResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasHasMore_:1;
  BOOL hasMore_:1;
  NSMutableArray * membersArray;
}
- (BOOL) hasHasMore;
@property (readonly, strong) NSArray * members;
- (BOOL) hasMore;
- (XCSDPBHomeworkMember*)membersAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBHomeworkMemberListResponseBuilder*) builder;
+ (XCSDPBHomeworkMemberListResponseBuilder*) builder;
+ (XCSDPBHomeworkMemberListResponseBuilder*) builderWithPrototype:(XCSDPBHomeworkMemberListResponse*) prototype;
- (XCSDPBHomeworkMemberListResponseBuilder*) toBuilder;

+ (XCSDPBHomeworkMemberListResponse*) parseFromData:(NSData*) data;
+ (XCSDPBHomeworkMemberListResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkMemberListResponse*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBHomeworkMemberListResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkMemberListResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBHomeworkMemberListResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBHomeworkMemberListResponseBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBHomeworkMemberListResponse* resultHomeworkMemberListResponse;
}

- (XCSDPBHomeworkMemberListResponse*) defaultInstance;

- (XCSDPBHomeworkMemberListResponseBuilder*) clear;
- (XCSDPBHomeworkMemberListResponseBuilder*) clone;

- (XCSDPBHomeworkMemberListResponse*) build;
- (XCSDPBHomeworkMemberListResponse*) buildPartial;

- (XCSDPBHomeworkMemberListResponseBuilder*) mergeFrom:(XCSDPBHomeworkMemberListResponse*) other;
- (XCSDPBHomeworkMemberListResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBHomeworkMemberListResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)members;
- (XCSDPBHomeworkMember*)membersAtIndex:(NSUInteger)index;
- (XCSDPBHomeworkMemberListResponseBuilder *)addMembers:(XCSDPBHomeworkMember*)value;
- (XCSDPBHomeworkMemberListResponseBuilder *)setMembersArray:(NSArray *)array;
- (XCSDPBHomeworkMemberListResponseBuilder *)clearMembers;

- (BOOL) hasHasMore;
- (BOOL) hasMore;
- (XCSDPBHomeworkMemberListResponseBuilder*) setHasMore:(BOOL) value;
- (XCSDPBHomeworkMemberListResponseBuilder*) clearHasMore;
@end

#define GenerateHomeworkRequest_classId @"classId"
@interface XCSDPBGenerateHomeworkRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasClassId_:1;
  SInt64 classId;
}
- (BOOL) hasClassId;
@property (readonly) SInt64 classId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBGenerateHomeworkRequestBuilder*) builder;
+ (XCSDPBGenerateHomeworkRequestBuilder*) builder;
+ (XCSDPBGenerateHomeworkRequestBuilder*) builderWithPrototype:(XCSDPBGenerateHomeworkRequest*) prototype;
- (XCSDPBGenerateHomeworkRequestBuilder*) toBuilder;

+ (XCSDPBGenerateHomeworkRequest*) parseFromData:(NSData*) data;
+ (XCSDPBGenerateHomeworkRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBGenerateHomeworkRequest*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBGenerateHomeworkRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBGenerateHomeworkRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBGenerateHomeworkRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBGenerateHomeworkRequestBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBGenerateHomeworkRequest* resultGenerateHomeworkRequest;
}

- (XCSDPBGenerateHomeworkRequest*) defaultInstance;

- (XCSDPBGenerateHomeworkRequestBuilder*) clear;
- (XCSDPBGenerateHomeworkRequestBuilder*) clone;

- (XCSDPBGenerateHomeworkRequest*) build;
- (XCSDPBGenerateHomeworkRequest*) buildPartial;

- (XCSDPBGenerateHomeworkRequestBuilder*) mergeFrom:(XCSDPBGenerateHomeworkRequest*) other;
- (XCSDPBGenerateHomeworkRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBGenerateHomeworkRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasClassId;
- (SInt64) classId;
- (XCSDPBGenerateHomeworkRequestBuilder*) setClassId:(SInt64) value;
- (XCSDPBGenerateHomeworkRequestBuilder*) clearClassId;
@end

#define GenerateHomeworkResponse_userHomeworks @"userHomeworks"
@interface XCSDPBGenerateHomeworkResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * userHomeworksArray;
}
@property (readonly, strong) NSArray * userHomeworks;
- (XCSDPBGenerateHomeworkResponseUserHomework*)userHomeworksAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBGenerateHomeworkResponseBuilder*) builder;
+ (XCSDPBGenerateHomeworkResponseBuilder*) builder;
+ (XCSDPBGenerateHomeworkResponseBuilder*) builderWithPrototype:(XCSDPBGenerateHomeworkResponse*) prototype;
- (XCSDPBGenerateHomeworkResponseBuilder*) toBuilder;

+ (XCSDPBGenerateHomeworkResponse*) parseFromData:(NSData*) data;
+ (XCSDPBGenerateHomeworkResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBGenerateHomeworkResponse*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBGenerateHomeworkResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBGenerateHomeworkResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBGenerateHomeworkResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define UserHomework_childUserId @"childUserId"
#define UserHomework_name @"name"
#define UserHomework_avatar @"avatar"
#define UserHomework_generateCount @"generateCount"
#define UserHomework_remainMaxCount @"remainMaxCount"
#define UserHomework_specialAttention @"specialAttention"
@interface XCSDPBGenerateHomeworkResponseUserHomework : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSpecialAttention_:1;
  BOOL hasChildUserId_:1;
  BOOL hasGenerateCount_:1;
  BOOL hasRemainMaxCount_:1;
  BOOL hasName_:1;
  BOOL hasAvatar_:1;
  BOOL specialAttention_:1;
  SInt64 childUserId;
  SInt32 generateCount;
  SInt32 remainMaxCount;
  NSString* name;
  NSString* avatar;
}
- (BOOL) hasChildUserId;
- (BOOL) hasName;
- (BOOL) hasAvatar;
- (BOOL) hasGenerateCount;
- (BOOL) hasRemainMaxCount;
- (BOOL) hasSpecialAttention;
@property (readonly) SInt64 childUserId;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* avatar;
@property (readonly) SInt32 generateCount;
@property (readonly) SInt32 remainMaxCount;
- (BOOL) specialAttention;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) builder;
+ (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) builder;
+ (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) builderWithPrototype:(XCSDPBGenerateHomeworkResponseUserHomework*) prototype;
- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) toBuilder;

+ (XCSDPBGenerateHomeworkResponseUserHomework*) parseFromData:(NSData*) data;
+ (XCSDPBGenerateHomeworkResponseUserHomework*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBGenerateHomeworkResponseUserHomework*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBGenerateHomeworkResponseUserHomework*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBGenerateHomeworkResponseUserHomework*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBGenerateHomeworkResponseUserHomework*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBGenerateHomeworkResponseUserHomeworkBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBGenerateHomeworkResponseUserHomework* resultUserHomework;
}

- (XCSDPBGenerateHomeworkResponseUserHomework*) defaultInstance;

- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) clear;
- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) clone;

- (XCSDPBGenerateHomeworkResponseUserHomework*) build;
- (XCSDPBGenerateHomeworkResponseUserHomework*) buildPartial;

- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) mergeFrom:(XCSDPBGenerateHomeworkResponseUserHomework*) other;
- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChildUserId;
- (SInt64) childUserId;
- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) setChildUserId:(SInt64) value;
- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) clearChildUserId;

- (BOOL) hasName;
- (NSString*) name;
- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) setName:(NSString*) value;
- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) clearName;

- (BOOL) hasAvatar;
- (NSString*) avatar;
- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) setAvatar:(NSString*) value;
- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) clearAvatar;

- (BOOL) hasGenerateCount;
- (SInt32) generateCount;
- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) setGenerateCount:(SInt32) value;
- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) clearGenerateCount;

- (BOOL) hasRemainMaxCount;
- (SInt32) remainMaxCount;
- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) setRemainMaxCount:(SInt32) value;
- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) clearRemainMaxCount;

- (BOOL) hasSpecialAttention;
- (BOOL) specialAttention;
- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) setSpecialAttention:(BOOL) value;
- (XCSDPBGenerateHomeworkResponseUserHomeworkBuilder*) clearSpecialAttention;
@end

@interface XCSDPBGenerateHomeworkResponseBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBGenerateHomeworkResponse* resultGenerateHomeworkResponse;
}

- (XCSDPBGenerateHomeworkResponse*) defaultInstance;

- (XCSDPBGenerateHomeworkResponseBuilder*) clear;
- (XCSDPBGenerateHomeworkResponseBuilder*) clone;

- (XCSDPBGenerateHomeworkResponse*) build;
- (XCSDPBGenerateHomeworkResponse*) buildPartial;

- (XCSDPBGenerateHomeworkResponseBuilder*) mergeFrom:(XCSDPBGenerateHomeworkResponse*) other;
- (XCSDPBGenerateHomeworkResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBGenerateHomeworkResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)userHomeworks;
- (XCSDPBGenerateHomeworkResponseUserHomework*)userHomeworksAtIndex:(NSUInteger)index;
- (XCSDPBGenerateHomeworkResponseBuilder *)addUserHomeworks:(XCSDPBGenerateHomeworkResponseUserHomework*)value;
- (XCSDPBGenerateHomeworkResponseBuilder *)setUserHomeworksArray:(NSArray *)array;
- (XCSDPBGenerateHomeworkResponseBuilder *)clearUserHomeworks;
@end

#define SendHomeworkRequest_classId @"classId"
#define SendHomeworkRequest_scope @"scope"
@interface XCSDPBSendHomeworkRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasClassId_:1;
  BOOL hasScope_:1;
  SInt64 classId;
  XCSDPBStudentScope scope;
}
- (BOOL) hasClassId;
- (BOOL) hasScope;
@property (readonly) SInt64 classId;
@property (readonly) XCSDPBStudentScope scope;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBSendHomeworkRequestBuilder*) builder;
+ (XCSDPBSendHomeworkRequestBuilder*) builder;
+ (XCSDPBSendHomeworkRequestBuilder*) builderWithPrototype:(XCSDPBSendHomeworkRequest*) prototype;
- (XCSDPBSendHomeworkRequestBuilder*) toBuilder;

+ (XCSDPBSendHomeworkRequest*) parseFromData:(NSData*) data;
+ (XCSDPBSendHomeworkRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBSendHomeworkRequest*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBSendHomeworkRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBSendHomeworkRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBSendHomeworkRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBSendHomeworkRequestBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBSendHomeworkRequest* resultSendHomeworkRequest;
}

- (XCSDPBSendHomeworkRequest*) defaultInstance;

- (XCSDPBSendHomeworkRequestBuilder*) clear;
- (XCSDPBSendHomeworkRequestBuilder*) clone;

- (XCSDPBSendHomeworkRequest*) build;
- (XCSDPBSendHomeworkRequest*) buildPartial;

- (XCSDPBSendHomeworkRequestBuilder*) mergeFrom:(XCSDPBSendHomeworkRequest*) other;
- (XCSDPBSendHomeworkRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBSendHomeworkRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasClassId;
- (SInt64) classId;
- (XCSDPBSendHomeworkRequestBuilder*) setClassId:(SInt64) value;
- (XCSDPBSendHomeworkRequestBuilder*) clearClassId;

- (BOOL) hasScope;
- (XCSDPBStudentScope) scope;
- (XCSDPBSendHomeworkRequestBuilder*) setScope:(XCSDPBStudentScope) value;
- (XCSDPBSendHomeworkRequestBuilder*) clearScope;
@end

@interface XCSDPBSendHomeworkResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBSendHomeworkResponseBuilder*) builder;
+ (XCSDPBSendHomeworkResponseBuilder*) builder;
+ (XCSDPBSendHomeworkResponseBuilder*) builderWithPrototype:(XCSDPBSendHomeworkResponse*) prototype;
- (XCSDPBSendHomeworkResponseBuilder*) toBuilder;

+ (XCSDPBSendHomeworkResponse*) parseFromData:(NSData*) data;
+ (XCSDPBSendHomeworkResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBSendHomeworkResponse*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBSendHomeworkResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBSendHomeworkResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBSendHomeworkResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBSendHomeworkResponseBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBSendHomeworkResponse* resultSendHomeworkResponse;
}

- (XCSDPBSendHomeworkResponse*) defaultInstance;

- (XCSDPBSendHomeworkResponseBuilder*) clear;
- (XCSDPBSendHomeworkResponseBuilder*) clone;

- (XCSDPBSendHomeworkResponse*) build;
- (XCSDPBSendHomeworkResponse*) buildPartial;

- (XCSDPBSendHomeworkResponseBuilder*) mergeFrom:(XCSDPBSendHomeworkResponse*) other;
- (XCSDPBSendHomeworkResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBSendHomeworkResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define HomeworkRemainingCountRequest_classId @"classId"
@interface XCSDPBHomeworkRemainingCountRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasClassId_:1;
  SInt64 classId;
}
- (BOOL) hasClassId;
@property (readonly) SInt64 classId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBHomeworkRemainingCountRequestBuilder*) builder;
+ (XCSDPBHomeworkRemainingCountRequestBuilder*) builder;
+ (XCSDPBHomeworkRemainingCountRequestBuilder*) builderWithPrototype:(XCSDPBHomeworkRemainingCountRequest*) prototype;
- (XCSDPBHomeworkRemainingCountRequestBuilder*) toBuilder;

+ (XCSDPBHomeworkRemainingCountRequest*) parseFromData:(NSData*) data;
+ (XCSDPBHomeworkRemainingCountRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkRemainingCountRequest*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBHomeworkRemainingCountRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkRemainingCountRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBHomeworkRemainingCountRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBHomeworkRemainingCountRequestBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBHomeworkRemainingCountRequest* resultHomeworkRemainingCountRequest;
}

- (XCSDPBHomeworkRemainingCountRequest*) defaultInstance;

- (XCSDPBHomeworkRemainingCountRequestBuilder*) clear;
- (XCSDPBHomeworkRemainingCountRequestBuilder*) clone;

- (XCSDPBHomeworkRemainingCountRequest*) build;
- (XCSDPBHomeworkRemainingCountRequest*) buildPartial;

- (XCSDPBHomeworkRemainingCountRequestBuilder*) mergeFrom:(XCSDPBHomeworkRemainingCountRequest*) other;
- (XCSDPBHomeworkRemainingCountRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBHomeworkRemainingCountRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasClassId;
- (SInt64) classId;
- (XCSDPBHomeworkRemainingCountRequestBuilder*) setClassId:(SInt64) value;
- (XCSDPBHomeworkRemainingCountRequestBuilder*) clearClassId;
@end

#define HomeworkRemainingCountResponse_customizedStatus @"customizedStatus"
#define HomeworkRemainingCountResponse_unifiedCount @"unifiedCount"
@interface XCSDPBHomeworkRemainingCountResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCustomizedStatus_:1;
  BOOL hasUnifiedCount_:1;
  BOOL customizedStatus_:1;
  SInt32 unifiedCount;
}
- (BOOL) hasCustomizedStatus;
- (BOOL) hasUnifiedCount;
- (BOOL) customizedStatus;
@property (readonly) SInt32 unifiedCount;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (XCSDPBHomeworkRemainingCountResponseBuilder*) builder;
+ (XCSDPBHomeworkRemainingCountResponseBuilder*) builder;
+ (XCSDPBHomeworkRemainingCountResponseBuilder*) builderWithPrototype:(XCSDPBHomeworkRemainingCountResponse*) prototype;
- (XCSDPBHomeworkRemainingCountResponseBuilder*) toBuilder;

+ (XCSDPBHomeworkRemainingCountResponse*) parseFromData:(NSData*) data;
+ (XCSDPBHomeworkRemainingCountResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkRemainingCountResponse*) parseFromInputStream:(NSInputStream*) input;
+ (XCSDPBHomeworkRemainingCountResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (XCSDPBHomeworkRemainingCountResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (XCSDPBHomeworkRemainingCountResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface XCSDPBHomeworkRemainingCountResponseBuilder : PBGeneratedMessageBuilder {
@private
  XCSDPBHomeworkRemainingCountResponse* resultHomeworkRemainingCountResponse;
}

- (XCSDPBHomeworkRemainingCountResponse*) defaultInstance;

- (XCSDPBHomeworkRemainingCountResponseBuilder*) clear;
- (XCSDPBHomeworkRemainingCountResponseBuilder*) clone;

- (XCSDPBHomeworkRemainingCountResponse*) build;
- (XCSDPBHomeworkRemainingCountResponse*) buildPartial;

- (XCSDPBHomeworkRemainingCountResponseBuilder*) mergeFrom:(XCSDPBHomeworkRemainingCountResponse*) other;
- (XCSDPBHomeworkRemainingCountResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (XCSDPBHomeworkRemainingCountResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCustomizedStatus;
- (BOOL) customizedStatus;
- (XCSDPBHomeworkRemainingCountResponseBuilder*) setCustomizedStatus:(BOOL) value;
- (XCSDPBHomeworkRemainingCountResponseBuilder*) clearCustomizedStatus;

- (BOOL) hasUnifiedCount;
- (SInt32) unifiedCount;
- (XCSDPBHomeworkRemainingCountResponseBuilder*) setUnifiedCount:(SInt32) value;
- (XCSDPBHomeworkRemainingCountResponseBuilder*) clearUnifiedCount;
@end


// @@protoc_insertion_point(global_scope)
